### ISSUE TITLE
Controller for demo creation

### ISSUE THREAD

**Issue by vonHartz** [haosulab/ManiSkill#100]
Great work on the benchmarks.

Do you mind releasing the code of the MPC controller used for generating the demonstrations?

The used controller seems to generate pretty jerky trajectories.

Consider this plot showing the actions (x, y, z velocity) for a set of demos for LiftCube.
X-axis is time.
![image](https://github.com/haosulab/ManiSkill2/assets/17391760/49d11f85-dbd5-4bf2-8a5e-64321a7f600c)

I would like to dampen the controller to generate smoother trajectories, that are better suited to fit GMMs.

Thanks in advance!

**Comment by xuanlinli17** [comment]
LiftCube demos were not generated with MPC. They were generated with motion planning. MPC was used to generate some demos in TurnFaucet as well as OpenCabinetDoor/Drawer, PushChair, MoveBucket.

Currently for fair evaluations of the challenge we don't have recent plans to release demo generation code yet.

**Comment by vonHartz** [comment]
Thanks for the reply!

Actually, the trajectories aren't as jerky, but it was due to a bug on my side. Apologies!
