### ISSUE TITLE
How to use a more realistic environment?

### ISSUE THREAD

**Issue by yangsizhe** [haosulab/ManiSkill#105]
Glad to see a wonderful simulation tool!
I noticed that the environment shown in the Github teaser (https://github.com/haosulab/ManiSkill2/blob/main/figures/teaser_v2.jpg) looks much more realistic than the environment shown on the website (https://sapien.ucsd.edu/challenges/maniskill/#getting-started). What is the reason for this, and how to use the realistic environment shown in the teaser?

**Comment by xuanlinli17** [comment]
The scenes are for illustration purposes. However, the scenes cannot be released due to licenses. We do provide a tutorial to add custom scenes here: https://github.com/haosulab/ManiSkill2/blob/main/examples/tutorials/customize_environments.ipynb

**Comment by yangsizhe** [comment]
Thank you!
