### ISSUE TITLE
Setting scales for objects

### ISSUE THREAD

**Issue by yichao-liang** [haosulab/ManiSkill#106]
I was wondering if there is any generic way for setting objects' scale in a scene, e.g. the cube's scale in PickCube-v0, and the object's scale in PickSingleYCB-v0, for domain randomization?

Thanks so much!

**Comment by xuanlinli17** [comment]
For PickCube, you can inherit the environment and change the `self.cube_half_size` (see [here](https://github.com/haosulab/ManiSkill2/blob/fc08823bf96791946591a508f336d724fa7cad26/mani_skill2/envs/pick_and_place/pick_cube.py#L21))

For PickSingleYCB, you just need to pass in `model_id` and `model_scale` in the reset function (see [here](https://github.com/haosulab/ManiSkill2/blob/fc08823bf96791946591a508f336d724fa7cad26/mani_skill2/envs/pick_and_place/pick_single.py#L85))
