### ISSUE TITLE
could you tell me where the PD controller  code ?

### ISSUE THREAD

**Issue by Jinming-Li** [haosulab/ManiSkill#109]
I hope to deploy the agent trained by maniskill2 to a real machine .is there any documentation or code to learn ?

**Comment by xuanlinli17** [comment]
It's here: https://github.com/haosulab/ManiSkill2/tree/main/mani_skill2/agents/controllers

**Comment by xuanlinli17** [comment]
Documentation: https://haosulab.github.io/ManiSkill2/concepts/controllers.html

**Comment by Jinming-Li** [comment]
Thank you for your prompt reply

**Comment by Jinming-Li** [comment]
>  PD controller: control loop based on $F(t) = K_p (\bar{q}(t) - q(t)) + K_d (\bar{\dot{q}}(t) - \dot{q}(t))$. $K_p$ (stiffness) and $K_d$ (damping) are hyperparameters. $F(t)$ is the force of the motor. 

I want to know the number of the   $K_p$  and $K_d$  .  If I want to carry on a real robot experiment, How can I implement the PD controller method mentioned here?

**Comment by xuanlinli17** [comment]
Stiffness and damping parameters are in the agent config files:

e.g., for stationary panda:

https://github.com/haosulab/ManiSkill2/blob/fc08823bf96791946591a508f336d724fa7cad26/mani_skill2/agents/configs/panda/defaults.py#L33

**Comment by Jinming-Li** [comment]
What are the units of the corresponding dimensions for each action

**Comment by xuanlinli17** [comment]
See https://github.com/haosulab/ManiSkill2/blob/fc08823bf96791946591a508f336d724fa7cad26/mani_skill2/agents/configs/panda/defaults.py

Actions [-1,1] are remapped to the lower and upper action limits. Joint positions are in rads. ee pos is in meters. ee rotation is in rads.

**Comment by Jinming-Li** [comment]
Thankyou

**Comment by kaijieshi7** [comment]
@xuanlinli17 .Hi, Can I ask you a question? If the real robot can reach the target position in given time, do i need to care about the damping and stiffness parameters in simulation? For example, the robot hand's finger can reach the target position in 0.2 seconds in real life.

**Comment by xuanlinli17** [comment]
In this case if the control is blocking, then you can just use the default parameters I think. As long as the joints reach the target position in a given time and matches the real behavior, control parameters don't matter too much.
