### ISSUE TITLE
When I run code on multiple GPUs, I get this error."

### ISSUE THREAD

**Issue by Jinming-Li** [haosulab/ManiSkill#110]
I run this code 
‘’‘
>python maniskill2_learn/apis/run_rl.py configs/brl/bc/rgbd.py \> --work-dir log/ceshi --gpu-ids 0 1  \> --cfg-options >"env_cfg.env_name=PickCube-v0" "env_cfg.obs_mode=rgbd" "env_cfg.n_points=1200" \
> "env_cfg.control_mode=pd_ee_delta_pose" \
> "replay_cfg.buffer_filenames=../ManiSkill2/demos/pickcube_trajectory_new1000.h5" \
> "eval_cfg.num=100" "eval_cfg.save_traj=False" "eval_cfg.save_video=False" \
> "train_cfg.n_eval=50000" "train_cfg.total_steps=50000" "train_cfg.n_checkpoint=50000" "train_cfg.n_updates=500"

’‘’
get： 

> ...
> '''
> PickCube-v0-train-0 - (run_rl.py:346) - INFO - 2023-07-13,23:48:32 - Config:
> agent_cfg = dict(
>     type='BC',
>     batch_size=256,
>     actor_cfg=dict(
>         type='ContinuousActor',
>         head_cfg=dict(type='TanhHead', noise_std=1e-05),
>         nn_cfg=dict(
>             type='Visuomotor',
>             visual_nn_cfg=dict(
>                 type='IMPALA',
>                 in_channel='image_channels',
>                 image_size='image_size',
>                 out_feature_size=384),
>             mlp_cfg=dict(
>                 type='LinearMLP',
>                 norm_cfg=None,
>                 mlp_spec=['384 + agent_shape', 256, 128, 'action_shape'],
>                 bias=True,
>                 inactivated_output=True)),
>         optim_cfg=dict(type='Adam', lr=0.0003)))
> env_cfg = dict(
>     type='gym',
>     env_name='PickCube-v0',
>     unwrapped=False,
>     obs_mode='rgbd',
>     n_points=1200,
>     control_mode='pd_ee_delta_pose',
>     device='cuda:0')
> replay_cfg = dict(
>     type='ReplayMemory',
>     capacity=8888,
>     num_samples=-1,
>     keys=['obs', 'actions', 'dones', 'episode_dones'],
>     buffer_filenames='../ManiSkill2/demos/pickcube_trajectory_new1000.h5')
> train_cfg = dict(
>     on_policy=False,
>     total_steps=50000,
>     warm_steps=0,
>     n_steps=0,
>     n_updates=500,
>     n_eval=50000,
>     n_checkpoint=50000)
> eval_cfg = dict(
>     type='Evaluation',
>     num=100,
>     num_procs=1,
>     use_hidden_state=False,
>     save_traj=False,
>     save_video=False,
>     use_log=False)
> work_dir = None
> resume_from = None
> expert_replay_cfg = None
> recent_traj_replay_cfg = None
> rollout_cfg = None
> 
> PickCube-v0-train-0 - (run_rl.py:347) - INFO - 2023-07-13,23:48:32 - Set random seed to 1526929559
> PickCube-v0-train-0 - (run_rl.py:351) - INFO - 2023-07-13,23:48:32 - Build replay buffer!
> PickCube-v0-train-0 - (replay_buffer.py:59) - INFO - 2023-07-13,23:48:32 - Load 1 files!
> PickCube-v0-train-0 - (logger.py:155) - INFO - 2023-07-13,23:48:32 - 0%|          | 0/1 [00:00<?, ?it/s]
> PickCube-v0-train-0 - (logger.py:155) - INFO - 2023-07-13,23:48:33 - 100%|##########| 1/1 [00:00<00:00,  1.78it/s]
> PickCube-v0-train-0 - (replay_buffer.py:62) - INFO - 2023-07-13,23:48:33 - Load 1 files with 48559 samples in total!
> PickCube-v0-train-0 - (replay_buffer.py:72) - WARNING - 2023-07-13,23:48:33 - You should use same the cache_size as the capacity when dynamically loading files!
> PickCube-v0-train-0 - (cache_utils.py:265) - INFO - 2023-07-13,23:48:34 - Lenght of cache: 8888, cache size 1390.3265838623047 MB, cache shape {'obs': {'depth': (8888, 2, 128, 128), 'rgb': (8888, 6, 128, 128), 'state': (8888, 38)}, 'actions': (8888, 7), 'dones': (8888, 1), 'episode_dones': (8888, 1), 'worker_indices': (8888, 1)}!
> PickCube-v0-train-0 - (replay_buffer.py:89) - INFO - 2023-07-13,23:48:34 - Finish building file cache!
> PickCube-v0-train-0 - (run_rl.py:383) - INFO - 2023-07-13,23:49:10 - Build evaluation!
> PickCube-v0-train-0 - (run_rl.py:392) - INFO - 2023-07-13,23:49:10 - Building evaluation: eval_cfg: {'type': 'Evaluation', 'num': 100, 'num_procs': 1, 'use_hidden_state': False, 'save_traj': False, 'save_video': False, 'use_log': False, 'env_cfg': {'type': 'gym', 'env_name': 'PickCube-v0', 'unwrapped': False, 'obs_mode': 'rgbd', 'n_points': 1200, 'control_mode': 'pd_ee_delta_pose', 'device': 'cuda:0'}}
> [2023-07-13 23:49:11.448] [svulkan2] [error] GLFW error: X11: Failed to open display 0
> [2023-07-13 23:49:11.448] [svulkan2] [warning] Continue without GLFW.
> [2023-07-13 23:49:11.505] [svulkan2] [error] GLFW error: X11: Failed to open display 0
> [2023-07-13 23:49:11.505] [svulkan2] [warning] Continue without GLFW.
> Evaluation-PickCube-v0-train-0-env - (evaluation.py:290) - INFO - 2023-07-13,23:49:14 - The Evaluation environment has seed in 807448122!
> PickCube-v0-train-0 - (run_rl.py:402) - INFO - 2023-07-13,23:49:14 - Get obs shape!
> PickCube-v0-train-0 - (env_utils.py:94) - INFO - 2023-07-13,23:49:14 - Environment has the continuous action space with dimension 7.
> PickCube-v0-train-0 - (run_rl.py:414) - INFO - 2023-07-13,23:49:14 - State shape:{'rgb': [6, 128, 128], 'depth': [2, 128, 128], 'state': 38}, action shape:7
> Spconv is not installed!
> No module named 'torchsparse'
> Pointnet++ is not compiled
> No module named 'maniskill2_learn.networks.modules.pn2_modules'
> Spconv is not installed!
> No module named 'torchsparse'
> Pointnet++ is not compiled
> No module named 'maniskill2_learn.networks.modules.pn2_modules'
> SparseConv is not supported
> No module named 'torchsparse'
> PickCube-v0-train-0 - (run_rl.py:427) - INFO - 2023-07-13,23:49:15 - Final agent config:
> {'type': 'BC', 'batch_size': 256, 'actor_cfg': {'type': 'ContinuousActor', 'head_cfg': {'type': 'TanhHead', 'noise_std': 1e-05}, 'nn_cfg': {'type': 'Visuomotor', 'visual_nn_cfg': {'type': 'IMPALA', 'in_channel': 8, 'image_size': [128, 128], 'out_feature_size': 384}, 'mlp_cfg': {'type': 'LinearMLP', 'norm_cfg': None, 'mlp_spec': [422, 256, 128, 7], 'bias': True, 'inactivated_output': True}}, 'optim_cfg': {'type': 'Adam', 'lr': 0.0003}}, 'env_params': {'obs_shape': {'rgb': [6, 128, 128], 'depth': [2, 128, 128], 'state': 38}, 'action_shape': 7, 'action_space': Box([-1. -1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1. 1.], (7,), float32), 'is_discrete': False}}
> PickCube-v0-train-0 - (collect_env.py:133) - INFO - 2023-07-13,23:49:15 - meta_collect_time: 2023-07-13-08:49:15
> PickCube-v0-train-0 - (collect_env.py:133) - INFO - 2023-07-13,23:49:15 - PYRL: version: 1.8.0b0
> PickCube-v0-train-0 - (collect_env.py:133) - INFO - 2023-07-13,23:49:15 - ManiSkill2: 
> PickCube-v0-train-0 - (run_rl.py:243) - INFO - 2023-07-13,23:49:15 - Initialize torch!
> PickCube-v0-train-0 - (run_rl.py:245) - INFO - 2023-07-13,23:49:15 - Finish Initialize torch!
> PickCube-v0-train-0 - (run_rl.py:253) - INFO - 2023-07-13,23:49:15 - Build agent!
> PickCube-v0-train-0 - (run_rl.py:257) - INFO - 2023-07-13,23:49:15 - BC(
>   (actor): ContinuousActor(
>     (backbone): Visuomotor(
>       (visual_nn): IMPALA(
>         (stem): Conv2d(8, 64, kernel_size=(4, 4), stride=(4, 4))
>         (feat_convs): ModuleList(
>           (0): Sequential(
>             (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>             (1): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
>           )
>           (1): Sequential(
>             (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>             (1): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
>           )
>           (2): Sequential(
>             (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>             (1): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
>           )
>         )
>         (resnet1): ModuleList(
>           (0): Sequential(
>             (0): ReLU()
>             (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>             (2): ReLU()
>             (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>           )
>           (1): Sequential(
>             (0): ReLU()
>             (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>             (2): ReLU()
>             (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>           )
>           (2): Sequential(
>             (0): ReLU()
>             (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>             (2): ReLU()
>             (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>           )
>         )
>         (resnet2): ModuleList(
>           (0): Sequential(
>             (0): ReLU()
>             (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>             (2): ReLU()
>             (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>           )
>           (1): Sequential(
>             (0): ReLU()
>             (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>             (2): ReLU()
>             (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>           )
>           (2): Sequential(
>             (0): ReLU()
>             (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>             (2): ReLU()
>             (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>           )
>         )
>         (fc): Linear(in_features=1024, out_features=384, bias=True)
>       )
>       (final_mlp): LinearMLP(
>         (mlp): Sequential(
>           (linear0): Linear(in_features=422, out_features=256, bias=True)
>           (act0): ReLU()
>           (linear1): Linear(in_features=256, out_features=128, bias=True)
>           (act1): ReLU()
>           (linear2): Linear(in_features=128, out_features=7, bias=True)
>         )
>       )
>     )
>     (head): TanhHead()
>   )
> )
> PickCube-v0-train-0 - (run_rl.py:258) - INFO - 2023-07-13,23:49:15 - Num of parameters: 1.05M, Model Size: 4.19M
> SparseConv is not supported
> No module named 'torchsparse'
> PickCube-v0-train-0 - (run_rl.py:271) - INFO - 2023-07-13,23:49:16 - Setting DDP!
> PickCube-v0-train-0 - (run_rl.py:286) - INFO - 2023-07-13,23:49:16 - Work directory of this run log/ceshi
> PickCube-v0-train-0 - (run_rl.py:288) - INFO - 2023-07-13,23:49:16 - Train over GPU [0, 1]!
> PickCube-v0-train-0 - (train_rl.py:186) - INFO - 2023-07-13,23:49:16 - Loaded replay buffer shape: {'obs': {'depth': (8888, 2, 128, 128), 'rgb': (8888, 6, 128, 128), 'state': (8888, 38)}, 'actions': (8888, 7), 'dones': (8888, 1), 'episode_dones': (8888, 1), 'worker_indices': (8888, 1), 'is_truncated': (8888, 1)}!
> PickCube-v0-train-0 - (train_rl.py:241) - INFO - 2023-07-13,23:49:16 - Begin training!
> Exception ignored in: <function SharedGDict.__del__ at 0x7f7a401c6b80>
> Traceback (most recent call last):
>   File "/data/private/ljm/ManiSkill2-Learn/maniskill2_learn/utils/data/dict_array.py", line 928, in __del__
>   File "/data/private/ljm/ManiSkill2-Learn/maniskill2_learn/utils/data/dict_array.py", line 913, in _unlink
>   File "/opt/conda/lib/python3.8/multiprocessing/shared_memory.py", line 239, in unlink
> ImportError: sys.meta_path is None, Python is likely shutting down
> Exception ignored in: <function SharedGDict.__del__ at 0x7f8ab93d2b80>
> Traceback (most recent call last):
>   File "/data/private/ljm/ManiSkill2-Learn/maniskill2_learn/utils/data/dict_array.py", line 928, in __del__
>   File "/data/private/ljm/ManiSkill2-Learn/maniskill2_learn/utils/data/dict_array.py", line 913, in _unlink
>   File "/opt/conda/lib/python3.8/multiprocessing/shared_memory.py", line 239, in unlink
> ImportError: sys.meta_path is None, Python is likely shutting down
> Traceback (most recent call last):
>   File "maniskill2_learn/apis/run_rl.py", line 487, in <module>
>     main()
>   File "maniskill2_learn/apis/run_rl.py", line 450, in main
>     mp.spawn(run_one_process, args=(world_size, args, cfg), nprocs=world_size, join=True)
>   File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
>     while not context.join():
>   File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException: 
> '''
> -- Process 1 terminated with the following error:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>     fn(i, *args)
>   File "/data/private/ljm/ManiSkill2-Learn/maniskill2_learn/apis/run_rl.py", line 432, in run_one_process
>     main_rl(rollout, evaluator, replay, args, cfg, expert_replay=expert_replay, recent_traj_replay=recent_traj_replay)
>   File "/data/private/ljm/ManiSkill2-Learn/maniskill2_learn/apis/run_rl.py", line 293, in main_rl
>     train_rl(
>   File "/data/private/ljm/ManiSkill2-Learn/maniskill2_learn/apis/train_rl.py", line 336, in train_rl
>     training_infos = agent.update_parameters(replay, updates=total_updates)
>   File "/data/private/ljm/ManiSkill2-Learn/maniskill2_learn/methods/brl/bc.py", line 103, in update_parameters
>     [pred_dist, pred_action] = self.actor(sampled_batch["obs"], mode="dist_mean")
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 952, in forward
>     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
> RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
> making sure all `forward` function outputs participate in calculating loss. 
> If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
> Parameter indices which did not receive grad for rank 1: 40
>  In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
> 
> /opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 14 leaked shared_memory objects to clean up at shutdown
>   warnings.warn('resource_tracker: There appear to be %d '
> '''
> ...

**Comment by xuanlinli17** [comment]
It's a bug in ManiSkill2-Learn due to the unused parameters in `TanhHead` in DDP. We'll fix this later.

For now you can either

- use GaussianHead in https://github.com/haosulab/ManiSkill2-Learn/blob/main/configs/brl/bc/pointnet_soft_body.py
- use a single gpu for BC training
- add `find_unused_parameters=True` in https://github.com/haosulab/ManiSkill2-Learn/blob/83dfe26c73b6ce6b0388a0fa07493f340e36dd44/maniskill2_learn/utils/torch/module_utils.py#L302

**Comment by xuanlinli17** [comment]
Fixed ManiSkill2-Learn by adding `find_unused_parameters=True`

**Comment by Jinming-Li** [comment]
> Fixed ManiSkill2-Learn by adding `find_unused_parameters=True`

Thank you for your prompt reply
