### ISSUE TITLE
RL Colab tutorial doesn't work

### ISSUE THREAD

**Issue by jrabary** [haosulab/ManiSkill#114]
Does anyone manage to run the RL tutorial on Colab. I got `[Errno 104] Connection reset by peer` error when trying to run the section about setting up training and evaluation environment.

**Comment by StoneT2000** [comment]
Can you share the full error message? And what you ran?

**Comment by StoneT2000** [comment]
Actually upon further inspection, it seems likely that the stable baselines 3 package was upgraded recently causing some bugs. I will finish the #76 PR as soon as possible which upgrades ManiSkill2 to gymnasium and probably fixes most of the bugs

**Comment by jrabary** [comment]
I was just running the Colab notebook as is without any modification. The error I mentioned is when trying the state base PPO.

**Comment by jrabary** [comment]
It is possible to test this PR without waiting for the official merge ?

**Comment by StoneT2000** [comment]
I was hoping it is as simple as replacing the mani_skill pip install with one that pip installs directly from the PR's branch, but it doesn't seem to work due to a different bug so need to fix it as well. Working on it for the next few days

**Comment by StoneT2000** [comment]
@jrabary The tutorial SB3 code in the repo at examples/tutorials/reinforcement-learning should now be working well and training fast. You can checkout the code in the PR branch and try it yourself. The Colab code is still being debugged

**Comment by StoneT2000** [comment]
Ok the latest colab on the PR branch should now be working, you can check it out here: https://colab.research.google.com/github/haosulab/ManiSkill2/blob/0.5.0/examples/tutorials/2_reinforcement_learning.ipynb

**Comment by jrabary** [comment]
Thanks. I was able to run the PR branch locally.
