### ISSUE TITLE
Staging assets download

### ISSUE THREAD

**Issue by drklug** [haosulab/ManiSkill#115]
Thanks for the great work! I noticed that there are some cool staging backgrounds like the one you used in the [first image](https://github.com/haosulab/ManiSkill2/raw/main/figures/teaser_v2.jpg).  I'm wondering how can I download those cool staging assets? In utils/download_asset.py I cannot find any code related to it.

**Comment by StoneT2000** [comment]
We aren't able to provide some backgrounds are some are proprietary. We only provide one as an example in the repo, at the moment you will have to find some yourself / buy them.

**Comment by drklug** [comment]
I see, thank you for the info tho.
