### ISSUE TITLE
I want to convert the point cloud data of the SingleYCB environment that I collected into RGBD data.

### ISSUE THREAD

**Issue by Jinming-Li** [haosulab/ManiSkill#120]
"I want to convert the point cloud data of the SingleYCB environment that I collected into RGBD data. Is there any way to do this? I noticed that the YCB JSON file requires an obj_to_goal_pos. Is this the same as env.goal_pos that is directly obtained in the environment? Is there a difference in units?"

**Comment by xuanlinli17** [comment]
It might be better to create the environment under the rgbd observation mode by doing `env=gym.make(env_name, obs_mode='rgbd')`. Then, load the environment states from the demonstration json and h5 files, and save the rgbd observations from the environment using `env.get_obs()`. See https://github.com/haosulab/ManiSkill2-Learn/blob/main/tools/convert_state.py .
