### ISSUE TITLE
[Question] Adding Perturbation Force to the Robot

### ISSUE THREAD

**Issue by yichao-liang** [haosulab/ManiSkill#121]
Hello, 

I'm interested in finding a way to introduce perturbation force to the robot in order to simulate for example a nudge to the robotic arm. I want to add something like this during training, so the trained agent is more robust.

I found there is a `add_force_at_point` method for `ActorDynamicBase` class and `LinkBase` is a subclass of it. The robot is an instance of `Articulation` which has method `get_links` that returns a list of `LinkBase`s.

Based on this, I believe that if I can identify a point on the robot's surface, then I should be able to add a perturbation force to it by calling the `add_force_at_point` method, right? Is there an easy to find a point on the robot to add perturbations this way? Alternatively, if there are better approaches to achieve my goal, I would be grateful for any suggestions.

Thank you very much for your attention and support in advance!

**Comment by fbxiang** [comment]
The observations you made are 100% correct. `add_force_at_point` is exactly the function you would call if you want to add force at a point in space (e.g. poke the robot). However, it is sometimes inconvenient as you may not know where to put the point.

Another function `add_force_torque` allows you to apply force and torque at the center of mass of this link. If you want "random" perturbation, it would make sense to use this function by passing in random forces and torques in a certain range (which you should fine-tune). Note the forces added by both functions only last 1 time step.
