### ISSUE TITLE
Change of an asset size after vectorization

### ISSUE THREAD

**Issue by Yefanov** [haosulab/ManiSkill#124]
I encountered a strange behavior with the `TurnFaucet-v0` environment. When I wrap it in a vector environment, the camera configurations seem to change, resulting in significantly different images from the base and hand cameras (either the camera is too close to the faucet or the faucet appears much larger than the robot).

Here's the code to recreate the issue:

```python
import matplotlib.pyplot as plt
from mani_skill2.vector import make

# Create the vectorized environment
venv = make('TurnFaucet-v0', 2, obs_mode='rgbd', reward_mode='sparse')

# Reset the environment and get the initial observation
obs = venv.reset()

# Close the environment
venv.close()

# Display the image from the base camera
plt.imshow(obs['image']['base_camera']['rgb'].cpu().numpy()[1])
```
![image](https://github.com/haosulab/ManiSkill2/assets/62796258/08cf9d71-78a0-47ff-be79-6f4b522924e7)

Upon investigating the `mani_skill2/vector/registration.py` file, I discovered that the `env_fn` function generates the environment with correct images. However, both `RGBDVecEnv` and `VecEnv` produce environments with distorted ones.

Interestingly, the `LiftCube-v0` environment works perfectly fine.

Please note that to run the vectorized `TurnFaucet-v0` environment, you need to use the 0.5.0 branch or visit this GitHub repository: https://github.com/Yefanov/mani-skill2/tree/fix_vec_env

**Comment by StoneT2000** [comment]
Yes i think we also see this issue on our draft 0.5.0 update, we are investigating it now, thanks for bringing it up! Feel free to make a PR too if you wish, that would be greatly appreciated

**Comment by Yefanov** [comment]
Hello, the mentioned branch has already pulled in version 0.5.0. I have continued my investigation, and it seems that there is no problem with the camera configuration. Instead, there appears to be an enlargement of the faucet.

If you move the base camera far from the scene, it becomes clear that the faucet appears very large.

```python
import numpy as np
import matplotlib.pyplot as plt
from mani_skill2.vector import make
from mani_skill2.utils.sapien_utils import look_at

pose = look_at([-1.6, 0, 0.3], [0, 0, 0.1]) # default: pose=look_at([-0.4, 0, 0.3], [0, 0, 0.1])
camera_cfgs = {
        'base_camera': {
            'p': pose.p,
            'q': pose.q,
            'height': 1024,
            'width': 1024
            }
        }

venv = make('TurnFaucet-v0', 1, obs_mode='rgbd', reward_mode='sparse', camera_cfgs=camera_cfgs)
obs = venv.reset()
venv.close()
plt.imshow(obs['image']['base_camera']['rgb'].cpu().numpy()[0])
```
![image](https://github.com/haosulab/ManiSkill2/assets/62796258/7a2bd164-1177-40ef-93e0-37883fd737b4)

Comparing to the regular environment:
```python
pose = look_at([-1.6, 0, 0.3], [0, 0, 0.1])
camera_cfgs = {
        'base_camera': {
            'p': pose.p,
            'q': pose.q,
            'height': 1024,
            'width': 1024
            }
        }
env = gym.make('TurnFaucet-v0', obs_mode='rgbd', camera_cfgs=camera_cfgs)
obs = env.reset()
env.close()
plt.imshow(obs['image']['base_camera']['rgb'])
```
![image](https://github.com/haosulab/ManiSkill2/assets/62796258/4cb8510a-b911-4b4b-94e3-e52cfb2b2610)

**Comment by StoneT2000** [comment]
Yes I think this is the issue I have with turn faucet, trying to fix now in 0.5.0

**Comment by StoneT2000** [comment]
Ok the issue is with vecenv where the worker does not receive the reset command to reset and correct model size. Not sure why just yet

**Comment by StoneT2000** [comment]
Actually it looks like this bug also surfaced up in the previous version? Perhaps this is a larger bug than expected.

**Comment by Yefanov** [comment]
Hello, I have tested with most environments:

Based on 0.4.0:
- LiftCube, PickSingleYCB, PickClutterYCB, PlugCharger, PegInsertionSide: they look great.
- PickSingleEGAD: The EGAD object appears enlarged.
- AssemblingKits: The size is preserved, but the colors of the kits are lost, and strange walls are added to the scene.

Based on 0.4.0 (actually, I tested it only with a minor fix that was pulled into 0.5.0, so the problem is not in the 0.5.0 update):
- OpenCabinetDoor, OpenCabinetDrawer, PushChair: they look like the whole scene became larger or the camera closer. However, the relative sizes between the robot and objects are preserved.
- TurnFaucet, MoveBucket: The faucet and bucket are enlarged.

Here is some examples:
![image](https://github.com/haosulab/ManiSkill2/assets/62796258/019cf1a1-a7cf-4f12-b8e0-861eb82691cb)
![image](https://github.com/haosulab/ManiSkill2/assets/62796258/21146eee-48ac-4164-9d47-d6c228080100)

Here is comparison between before and after vectorization for OpenCabinetDrawer:
![image](https://github.com/haosulab/ManiSkill2/assets/62796258/841475f3-1e3c-431a-ba81-5d6fbe1d0f05)
![image](https://github.com/haosulab/ManiSkill2/assets/62796258/0987b83a-0938-4490-92ca-82b09e89847f)

**Comment by StoneT2000** [comment]
We've identified that there is a issue with sapien actually. Thanks for helping find all the scaling issues! We're fixing it soon

**Comment by StoneT2000** [comment]
@fbxiang just published a fix that should work on your code (and on our new 0.5.0 branch). Can you run `pip install sapien==2.2.2`?

**Comment by Yefanov** [comment]
Thank you! The assets for each environment are of the correct sizes. There is one small bug, which is preserved, however, where the kits from AssemblingKits appear grayish instead of being colorful.

**Comment by StoneT2000** [comment]
What do you mean by grayish?

**Comment by Yefanov** [comment]
Apologies for any confusion. What I meant to convey is that the assets appear grey instead of being colorful.
![image](https://github.com/haosulab/ManiSkill2/assets/62796258/9859408e-1b05-4aba-92ed-f0e48399cbb1)
