### ISSUE TITLE
Leak of GPU memory when using set_environment_map_from_files function

### ISSUE THREAD

**Issue by lyshuga** [haosulab/ManiSkill#133]
Hi,

We have observed one issue. After every reset it was applied "set_environment_map_from_files" to generate a new skybox, but unfortunately after every 10-20 reset the amount of GPU memory used increased by 100-200 MB. So, after let's say 100 resets we run out of GPU memory. The function "set_environment_map_from_files" is the wrapper for C++ function, I was wondering if it possible to somehow overcome this issue.

Thanks

**Comment by xuanlinli17** [comment]
Looks like the memory consumption is due to the cached resources. You can release the memory by

`env.unwrapped._renderer.clear_cached_resources()`

**Comment by StoneT2000** [comment]
Closing this issue as it has gone stale. Feel free to reopen if not.

**Comment by IrvingF7** [comment]
> Looks like the memory consumption is due to the cached resources. You can release the memory by
> 
> `env.unwrapped._renderer.clear_cached_resources()`

@StoneT2000 @xuanlinli17 
Hi, Sorry to dig up this old issue. I am facing something similar in that, whenever I make a new environment in a single process, I notice that my VRAM goes up, and it never comes down. Reset doesn't increase VRAM, but making a new env does. 

![Image](https://github.com/user-attachments/assets/e7684b92-ebbb-4bc0-91a6-08a31dfbc157)

As you can see, I run 60 parallel of env A for a total of 240 run, which is roughly 10 mins. Then I switch to another envs, rinse and repeat. Yet the VRAM also goes up like a staircase. I checked the time and I can confirm that the VARM only goes up when a new env is made

I tried this api but apparently it was not in the codebase anymore. Is there something similar that I can do? If you think this is an entirely different issues, I am more than happy to open a new independent issue.

Thanks in advance

**Comment by StoneT2000** [comment]
Will address this in the simpler-env repo
