### ISSUE TITLE
Assets and demos missing?

### ISSUE THREAD

**Issue by dennisushi** [haosulab/ManiSkill#14]
Hi, here's an error.

```
python tools/replay_trajectory.py --traj-path demos/rigid_body_envs/TurnFaucet-v0/20220815/5000.h5 --vis

AssertionError: ManiSkill2/mani_skill2/assets/partnet_mobility/dataset/5076/mobility_cvx.urdf is not found. Please download Partnet-Mobility (ManiSkill2022) first
```

Also, can't find the demonstrations for the rest of the articulated tasks. 

Generally, is there any visual variation in the task objcets? (e.g., different cubes/colour faucets like in the shelves from ManiSkill1)

**Comment by xuanlinli17** [comment]
Please run `python tools/download.py --uid faucet` to download the corresponding assets (see wiki).

Migration of other articulated tasks (from ManiSkill1 with improvements) are not finished yet. We expect to release them by the end of August.

`Generally, is there any visual variation in the task objects?`

Yes, all articulated tasks (e.g. TurnFaucet) have visual and geometry variations.

`AssemblingKits-v0`, `PickSingleYCB-v0`, `PickSingleEGAD-v0` `PandaAvoidObstacles-v0` also have visual and geometry variations.

For other tasks, while asset use is the same, there is significant configuration variations (e.g. 6D poses of objects, hole position in `PegInsertionSide-v0` and `PlugCharger-v0`, and the target criterion in soft-body tasks (see wiki for more details).

**Comment by Jiayuan-Gu** [comment]
Now you can use `python tools/download.py --uid all` to download assets.
