### ISSUE TITLE
http 404 when running `python -m mani_skill2.utils.download_demo PickSingleYCB-v0`

### ISSUE THREAD

**Issue by mlzxy** [haosulab/ManiSkill#140]
Error like this `urllib.error.HTTPError: HTTP Error 404: Not Found`. 

I verify this error on both local machine and remote server.

**Comment by xuanlinli17** [comment]
It works fine for me. Perhaps you need vpn to access google since the demos are stored on google drive?

**Comment by mlzxy** [comment]
Thank you for your reply. I am downloading the file overseas actually. 

 

I can download other trajectories but not this. Could you check huggingface again like here https://huggingface.co/datasets/haosulab/ManiSkill2/tree/main/demos/v0/rigid_body/PickSingleYCB-v0?  It contains a zip file instead of trajectory h5 and json. 

 

 

On Wed, Aug 23, 2023, 1:06 AM Xuanlin (Simon) Li ***@***.*** ***@***.***> > wrote:

It works fine for me. Perhaps you need vpn to access google since the demos are stored on google drive?

**Comment by StoneT2000** [comment]
Fixing the HF link now

**Comment by StoneT2000** [comment]
While we are waiting on a review and releasing the new pypi package to fix the bug, you may download the dataset yourself here: https://huggingface.co/datasets/haosulab/ManiSkill2/blob/main/demos/v0/rigid_body/PickSingleYCB-v0/PickSingleYCB-v0.zip

And unzip it to `demos/v0/rigid_body`

**Comment by mlzxy** [comment]
> While we are waiting on a review and releasing the new pypi package to fix the bug, you may download the dataset yourself here: https://huggingface.co/datasets/haosulab/ManiSkill2/blob/main/demos/v0/rigid_body/PickSingleYCB-v0/PickSingleYCB-v0.zip
> 
> And unzip it to `demos/v0/rigid_body`

Thanks for your guidance. Will do.

**Comment by StoneT2000** [comment]
closed with latest release 0.5.2
