### ISSUE TITLE
StackCube-v0 evaluate() method does not have consistent key names: "is_cubaA_grasped" instead of "is_cubeA_grasped""

### ISSUE THREAD

**Issue by mrodiduger** [haosulab/ManiSkill#142]
A really minor naming issue but should be changed in my opinion

https://github.com/haosulab/ManiSkill2/blob/231eb151b917ae68155a58fca88a6293e1f1ab03/mani_skill2/envs/pick_and_place/stack_cube.py#L119-L131

**Comment by StoneT2000** [comment]
Will be fixed! Thanks for bringing it up, we'll release the fix in 0.5.3
