### ISSUE TITLE
How to convert a world-frame pose to a pose in the robot frame?

### ISSUE THREAD

**Issue by arthur801031** [haosulab/ManiSkill#145]
In ManiSkill2's environments, we only know the object’s world-frame pose. I am trying to use motion planning to move the robot’s end-effector to that object; however, the [motion planning function](https://sapien.ucsd.edu/docs/latest/tutorial/motion_planning/plan_a_path.html#plan-with-sampling-based-algorithms) takes the target pose in the robot frame. How can I obtain this transformation matrix?

Thank you 🙏

**Comment by xuanlinli17** [comment]
`env.agent.robot.get_pose().inv() * env.unwrapped.obj.get_pose()`

This transforms object pose to robot base frame.
