### ISSUE TITLE
segmentation fault (core dumped), when an action filled with NaN is passed as parameter to env.step()

### ISSUE THREAD

**Issue by mrodiduger** [haosulab/ManiSkill#151]
Following code causes a "segmentation fault (core dumped)". Instead, it should raise an exception I think.

obs_mode = "state"
control_mode = "base_pd_joint_vel_arm_pd_joint_vel"
env_name = "PushChair-v1"

env = gym.make(env_name, obs_mode=obs_mode, control_mode=control_mode)
obs, _ = env.reset(seed=0)
a = np.empty((20))
a.fill(np.NaN)
print(a)
obs, reward, done, info = env.step(a)

**Comment by StoneT2000** [comment]
Thanks for bringing this up. We will add a fix in the next patch to throw an exception if there are any nan values.
