### ISSUE TITLE
Add a custom robot in the "Excavate-v0" environment, such as ur5

### ISSUE THREAD

**Issue by zqy-an** [haosulab/ManiSkill#154]
Hi,
How do I customize a robot in a soft-body environment?
Thanks.

**Comment by xuanlinli17** [comment]
Please see https://github.com/haosulab/ManiSkill2/blob/main/examples/tutorials/customize_environments.ipynb  for an example.

**Comment by zqy-an** [comment]
Thanks for your answer!

**Comment by StoneT2000** [comment]
In the coming weeks we will also begin slowly adding out of the box support for different robots, so stay tuned.

**Comment by 103240** [comment]
> 您好，如何在软体环境中定制机器人？ 谢谢。

请问您是否成功添加ur5我有些疑问向请教您，ur5在motion planner过程中使用screw总是规划失败，不知道您是否有遇到过这原因
