### ISSUE TITLE
How to use custom demonstrations from SAPIEN in ManiSkill2

### ISSUE THREAD

**Issue by JackMa-coder** [haosulab/ManiSkill#155]
Thank you for your exceptional contribution.
Can the custom demonstrations generated in the SAPIEN simulation environment be utilized for the learning from demonstrations method within the Maniskill2 framework? If so, could you kindly offer guidance on how to implement them? I would greatly appreciate any guidance you can provide.

**Comment by xuanlinli17** [comment]
Yes, please see [ManiSkill2-Learn](https://github.com/haosulab/ManiSkill2-Learn) DAPG / GAIL algorithms for reference.

**Comment by JackMa-coder** [comment]
That's reassuring. Thank you!
