### ISSUE TITLE
ERROR: [Loader Message] Code 0 : libGLX_nvidia.so.0: cannot open shared object 

### ISSUE THREAD

**Issue by chuanyune** [haosulab/ManiSkill#159]
I ran into this problem when I was running：

RuntimeError: vk::Instance::enumeratePhysicalDevices: ErrorInitializationFailed

Then I typed in vulkaninfo to see if vulkan would work, and it reported an error

ERROR: [Loader Message] Code 0 : libGLX_nvidia.so.0: cannot open shared object 

ubuntu22.04

**Comment by zyzshixiaobendan** [comment]
I am using nvidia 535.

**Comment by chuanyune** [comment]
I am using nvidia 535 and don't know what to do with it, help!

**Comment by xuanlinli17** [comment]
Hi, please follow https://haosulab.github.io/ManiSkill2/getting_started/installation.html#troubleshooting  for troubleshooting. You need to ensure the 3 json files exist.

**Comment by zyzshixiaobendan** [comment]
Thank you for your reply! If the three json files are set up will the file hold error also disappear?

**Comment by chuanyune** [comment]
Thank you for your reply! If the three json files are set up will the file hold error also disappear? @xuanlinli17

**Comment by xuanlinli17** [comment]
The error will most likely go away.

**Comment by chuanyune** [comment]
When I execute 'sudo apt-get install libglvnd-dev,' it doesn't generate the '10_nvidia.json' file. How can I resolve this? @xuanlinli17

**Comment by chuanyune** [comment]
You should reinstall vulkan if you get RuntimeError: vk::Instance::enumeratePhysicalDevices: ErrorInitializationFailed, and I've already reinstalled it and it still gives me the same error. I typed vulkaninfo into the terminal to see if vulkan could run properly and he reported ERROR: [Loader Message] Code 0 : libGLX_nvidia.so.0: cannot open shared object file: No such file or No such file or directory. Is the essential problem that this file is missing? Please help me to solve it, thanks! @xuanlinli17

**Comment by xuanlinli17** [comment]
If the 3 json files exist, then this is the essential problem. The file is missing. You can find a similar file in your system (`find / -name "libGLX_nvidia*"`) and symlink it to `libGLX_nvidia.so.0` (and modify the corresponding library path in `10_nvidia.json` to point to the correct location`. If no similar file exist, reinstall the nvidia driver.

**Comment by StoneT2000** [comment]
Closing this issue as it has gone stale. Feel free to reopen if not.
