### ISSUE TITLE
GPU 0 is always used in a multi-GPU setup

### ISSUE THREAD

**Issue by nikolai-franke** [haosulab/ManiSkill#161]
I'm working in a HPC environment where each node has 4 Nvidia A100 GPUs. The driver version is 525.105.17.
I try to run multiple parallel experiments, using multiple parallel ManiSkill2 environments each. To distribute them among the GPUs, I set the CUDA_VISIBLE_DEVICES environment variable. I would expect every run to use exactly one GPU, but this is not the case.

CUDA_VISIBLE_DEVICES=0: only GPU 0 is used
CUDA_VISIBLE_DEVICES=1: GPU 1 and GPU 0 are used
CUDA_VISIBLE_DEVICES=2: GPU 2 and GPU 0 are used
CUDA_VISIBLE_DEVICES=3: GPU 3 and GPU 0 are used

Not setting the environment variable, but providing the device to the SapienRenderer directly, i.e. instantiating it via `SapienRenderer(device="cuda:x")` results in the same behavior.

This severely limits the number of parallel environments I can use on a single compute node, since every environment does _something_ on GPU 0 and I run into resource limitations.

**Comment by StoneT2000** [comment]
@fbxiang any idea?

**Comment by fbxiang** [comment]
Can you try `SapienRenderer(offscreen_only=True, ...)`?
I think selecting a GPU that can potentially render to screen is at higher priority than the device argument. This behavior will be changed in future SAPIEN, but ManiSkill2 probably will not get this update.

**Comment by nikolai-franke** [comment]
I've already tried that, it does not make a difference. But even if it selected another GPU at a higher priority, it should always select **one** GPU, right? I don't understand why it would do work on two separate GPUs (and one of them always being GPU 0).

**Comment by nikolai-franke** [comment]
It seems to be a SAPIEN issue, as I can reproduce this behavior only using SAPIEN. I will open a new issue in the SAPIEN repo.
