### ISSUE TITLE
How to create a new envrionment from scratch.

### ISSUE THREAD

**Issue by Jiaviz** [haosulab/ManiSkill#163]
Your work is really impressive and lots of sample envs are provided. And I'd like to know how to build **a custom envrionment**, for example a env where **several cups** filled with liquid on a desk. 

Thanks!

**Comment by xuanlinli17** [comment]
Hi, thanks for your interest in our work! please refer to https://github.com/haosulab/ManiSkill2/blob/main/examples/tutorials/customize_environments.ipynb  for examples.

**Comment by StoneT2000** [comment]
We will be releasing some better template code in the future as well as part of the next maniskill, but for now you can use the current tutorials

**Comment by Jiaviz** [comment]
> We will be releasing some better template code in the future as well as part of the next maniskill, but for now you can use the current tutorials

Thanks for your reply. I'm looking forward to the futrue release🤗

**Comment by Jiaviz** [comment]
> Hi, thanks for your interest in our work! please refer to https://github.com/haosulab/ManiSkill2/blob/main/examples/tutorials/customize_environments.ipynb for examples.

Thanks for your reply🤗
