### ISSUE TITLE
Is there any way to set a moving camera in an environment?

### ISSUE THREAD

**Issue by HeegerGao** [haosulab/ManiSkill#164]
Hi, I found that in `sapien_env.py`, you said "Agent and camera configurations should not change after initialization". I wonder if there is any way to set up a moving camera that can move at every `env.step()` along a predefined trajectory. Thanks!

**Comment by xuanlinli17** [comment]
You can mount the camera to an actor. When the actor moves as the environment steps, the camera will move. (Side note: set the camera local pose with respect to the actor using `camera.set_local_pose`). See https://sapien.ucsd.edu/docs/2.0/tutorial/rendering/camera.html

**Comment by HeegerGao** [comment]
Thanks for your quick reply!
