### ISSUE TITLE
Do the segmentation masks for OpenCabinetDoor include the target door?

### ISSUE THREAD

**Issue by nikolai-franke** [haosulab/ManiSkill#167]
In ManiSkill 1, there were segmentation masks for the target handle included in the observations. Does one of the included segmentation masks in ManiSkill2 still include the target handle with a special class value?

**Comment by xuanlinli17** [comment]
In ManiSkill2, the default environment config does not include segmentation masks. However, you can add the segmentations based on the tutorial in https://haosulab.github.io/ManiSkill2/concepts/observation.html
