### ISSUE TITLE
How could I get the object's coordinate system

### ISSUE THREAD

**Issue by KarelZhang** [haosulab/ManiSkill#168]
In the first picture, we could get the position of the banana.
How could I get the banana's coordinate system just like the second picture?

![图片](https://github.com/haosulab/ManiSkill2/assets/26562112/46109bba-8428-44ba-9b03-f44bedb31679)
![图片](https://github.com/haosulab/ManiSkill2/assets/26562112/58de99ee-efb6-49c9-9802-256d182d92c1)

**Comment by xuanlinli17** [comment]
It's a bug of the sapien viewer. Deselect the coordinate axis on the left panel, then reselect it, then you will get the coordinate frame.

**Comment by xuanlinli17** [comment]
Also, the coordinate system of articulations and actors are right-handed, not left-handed.

**Comment by KarelZhang** [comment]
@xuanlinli17 Thank you so much!!!
