### ISSUE TITLE
Cannot find the green target in the two cameras in Pick env

### ISSUE THREAD

**Issue by jiechuanjiang** [haosulab/ManiSkill#171]
It seems that the agent cannot observe the green goal from the two cameras.

![rgbd](https://github.com/haosulab/ManiSkill2/assets/41461960/f59c4a4a-3868-491e-b8ad-c4bfcb67657e)

**Comment by xuanlinli17** [comment]
Yes, this is intended. The green sphere is only for visualization purpose. Though, you can add the green sphere manually in the point cloud observation (like in maniskill2-learn), which will be helpful for agent performance.
