### ISSUE TITLE
How do we get the ranges of the the observations?

### ISSUE THREAD

**Issue by vlongle** [haosulab/ManiSkill#172]
Hi,

Thank you for your work. From this code snippet,
```
import gymnasium as gym
import mani_skill2.envs

obs_mode = "state_dict"

env = gym.make("PickCube-v0", 
               obs_mode=obs_mode, control_mode="pd_joint_delta_pos", render_mode="rbg_array")
print("Observation space", env.observation_space)
print("Action space", env.action_space)

```
We see that all of the observation keys have ranges from -inf to inf, for instance `'qvel': Box(-inf, inf, (9,), float32)`. I'm wondering if there's a way to get a finite range such as `'qvel': Box(MIN_VEL, MAX_VEL, (9,), float32)`. We're interested in reconstructing these states (e.g., for things like model-based RL). Thank you!

**Comment by xuanlinli17** [comment]
The observation space is unbounded because qvel and object positions (in state observation mode), etc are unbounded. The qpos is bounded though, you can access the limits through `env.agent.robot.get_qlimits()`
