### ISSUE TITLE
Stains on objects

### ISSUE THREAD

**Issue by CyanWatts** [haosulab/ManiSkill#181]
Is there currently a way for Maniskill2 to add stains to objects (such as plates, tabletops, etc.) to define some tasks for cleaning stains? This scene is quite realistic.

**Comment by xuanlinli17** [comment]
Hi, you can manually modify objects in e.g., Blender and then load them into the benchmark by following the asset format in PickSingleYCB (and letting Blender export the appropriate files).

**Comment by CyanWatts** [comment]
> Hi, you can manually modify objects in e.g., Blender and then load them into the benchmark by following the asset format in PickSingleYCB (and letting Blender export the appropriate files).

Thanks for the reply! I'll try it.
