### ISSUE TITLE
VecEnv not working with MoveBucket-v1 for dense reward

### ISSUE THREAD

**Issue by yilin-wu98** [haosulab/ManiSkill#185]
Hi,

I see from the previous [ issue ](https://github.com/haosulab/ManiSkill2/issues/117#issuecomment-1649358200) that VecEnv for MoveBucket will return the error of "AttributeError: 'NoneType' object has no attribute 'vertices'" because the usage of dense reward requires the visual body mesh. However, for my case, I need to provide a dense reward signal for the agent to learn the policy for the task. Therefore, I am wondering if there is any alternative way that I can define a dense reward without using the visual body mesh. I am also wondering if your team is planning to add some alternative dense reward function compatible with the VecEnv.

Thanks

**Comment by tongzhoumu** [comment]
An alternative solution is that you can use gym's [AsyncVecEnv](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/vector/async_vector_env.py).

**Comment by yilin-wu98** [comment]
Thanks for your reply! If I still want to use the feature of gpu parallel rendering, do you have any advice on how I could bypass the use of the visual body mesh to get/write a dense reward function?

**Comment by tongzhoumu** [comment]
One possible solution is to pre-extract the needed information from the visual mesh and save it somewhere on the disk. When computing the dense reward, you just need to load that information. This solution requires a bit of engineering effort, and unfortunately, I don't have a better idea for now.

**Comment by StoneT2000** [comment]
Closing the issue for now as it is stale. Moreover we will be revamping many tasks in the near future so we will fix in the future
