### ISSUE TITLE
How to download the ignored files in the /mani_skill2/assets/ ?

### ISSUE THREAD

**Issue by swords123** [haosulab/ManiSkill#21]
I want to convert the demonstrations using:

> python tools/convert_state.py --env-name AssemblingKits-v0 --num-procs 8 \
>         --traj-name ../envs/rigid_body_envs/AssemblingKits-v0/trajectory.h5 \
>         --json-name ../envs/rigid_body_envs/AssemblingKits-v0/trajectory.json \
>         --output-name ../envs/rigid_body_envs/AssemblingKits-v0/trajectory_out.h5 \
>         --control-mode pd_joint_delta_pos --max-num-traj -1 --obs-mode pointcloud \
>         --n-points 1200 --obs-frame base --reward-mode dense 

However, the output is :
FileNotFoundError: [Errno 2] No such file or directory: '~/Work/Research/maniskill/ManiSkill2-main/mani_skill2/assets/assembling_kits/kits/kit_232.json'
How can I download these files.

**Comment by Jiayuan-Gu** [comment]
Please try `python tools/download.py --uid all`.
