### ISSUE TITLE
Rendering with kuafu of different size gives noisy image

### ISSUE THREAD

**Issue by Xingyu-Lin** [haosulab/ManiSkill#26]
With the kuafu renderer, I tried to change the default camera size from 512 to 1024. This is done by changing this line: https://github.com/haosulab/ManiSkill2/blob/787439b2484190bcbbca2e2daa9aa2cea38816be/mani_skill2/envs/experimental/turn_faucet.py#L74

However, I got noisy rendered results. See the noisy pixels in the sky. Do you know why this might happen?

![image](https://user-images.githubusercontent.com/11518107/190531426-20052378-8688-4863-91ab-c0c3cf99f17c.png)

**Comment by jetd1** [comment]
Thanks for this report. Can you reproduce the same artifacts every time you run the script? What happen if you change the viewing angle? Are these artifacts moving with the camera? Or are they taking up the same pixels?

**Comment by Xingyu-Lin** [comment]
I have not tried different viewing angles. But if I use a different resolution, the location of the artifacts will change

**Comment by Jiayuan-Gu** [comment]
Hi @Xingyu-Lin 

We have released `mani_skill2==0.4.0`. Fanbo has made efforts to integrate KuafuRenderer into VulkanRenderer, which is unified under `SapienRenderer`. More features and improvements are included in the new version. Please see the [release note](https://github.com/haosulab/ManiSkill2/releases/tag/v0.4.0) for details. Feel free to let us know what we can improve. Thank you.

**Comment by Xingyu-Lin** [comment]
Thanks, the new features look amazing!
