### ISSUE TITLE
Can not set the camera's intrinsic through camera_cfg

### ISSUE THREAD

**Issue by hzaskywalker** [haosulab/ManiSkill#266]
Currently the camera requires only one of intrinsic and fov is provided:
https://github.com/haosulab/ManiSkill2/blob/bae10d3a0d8b297e0254dae86a6805341df696be/mani_skill/sensors/camera.py#L138

But it always assumes fov is provided when creating cameras here:
https://github.com/haosulab/ManiSkill2/blob/bae10d3a0d8b297e0254dae86a6805341df696be/mani_skill/envs/scene.py#L176

**Comment by StoneT2000** [comment]
fixed by #267
