### ISSUE TITLE
The purpose of `inv_scale_action` in `replay_trajectory`

### ISSUE THREAD

**Issue by RogerChern** [haosulab/ManiSkill#269]
Kudos for the authors to develop this fantastic framework.

When I am reading the `mani_skill2/trajectory/replay_trajectory.py` code, I found one place especially alien to me.

After obtaining the `prev_pose_to_target_pose`(a.k.a. `ee_pose_at_ee`) , which is the pose delta that I think one would feed into a `PDEEPoseController` working in the delta mode. But instead, I found the code further process the `prev_pose_to_target_pose` by a `inv_scale_action` which just cancel out the normalization effect in the `set_action` method of controller. I further found that `assert controller.config.normalize_action` seems indicating that the code want the controller in normalization mode. So why do we ensure the normalization is on while cancel out the effect of normalization by `inv_scale_action`. Could we just use `controller.config.normalize_action = False`. 

Thanks again in advance.

https://github.com/haosulab/ManiSkill2/blob/6f84abacc8d3641bb70c37d4cd8f6b27bfe81bf6/mani_skill2/trajectory/replay_trajectory.py#L67C1-L83C1

**Comment by StoneT2000** [comment]
Sorry for the late reply. We likely won't set the normalize action config to False because the controller is supposed to accept delta, normalized actions, which is useful for most machine learning workflows.

**Comment by StoneT2000** [comment]
Closed in favor of #346 

The inverse scaling is necessary as for delta pose control the generated converted action from pd joint position control may be too large and so we need to scale it accordingly
