### ISSUE TITLE
Error of document

### ISSUE THREAD

**Issue by TinyDreamer1** [haosulab/ManiSkill#284]
It seems that I can't access the [document page](https://haosulab.github.io/ManiSkill2/), is there any error?

**Comment by xuanlinli17** [comment]
It's migrated to https://haosulab.github.io/ManiSkill/, but we'll update it to maniskill3 doc soon

**Comment by TinyDreamer1** [comment]
> It's migrated to https://haosulab.github.io/ManiSkill/, but we'll update it to maniskill3 doc soon

Thanks
