### ISSUE TITLE
Environments are only registered when importing BaseEnv

### ISSUE THREAD

**Issue by ottofabian** [haosulab/ManiSkill#300]
### Issue

Currently the provided environments are only registered when importing `BaseEnv`, i.e. the below snippet will throw a `gymnasium.error.NameNotFound`. 

```python

import gymnasium as gym
import mani_skill

env = gym.make("PushCube-v1")

```

However this will create the desired environment

```python

import gymnasium as gym
from mani_skill.envs.sapien_env import BaseEnv

env = gym.make("PushCube-v1")

```

I assume this happens due to `REGISTERED_AGENTS` being imported in the BaseEnv. 

### Expected behavior

Make environments available upon installation or by importing any part of mani_skill and not just by importing BaseEnv, which is likely not needed as import in most cases.

**Comment by xuanlinli17** [comment]
@StoneT2000 
Currently we support importing via `import mani_skill.envs`, see https://maniskill.readthedocs.io/en/latest/user_guide/getting_started/quickstart.html . But it's a good suggestion.
