### ISSUE TITLE
Command in the Document not Executable

### ISSUE THREAD

**Issue by BXZZcj** [haosulab/ManiSkill#316]
The command "python -m test.py -r "my_panda" -c "pd_joint_pos" --keyframe-actions" in the document (https://maniskill.readthedocs.io/en/latest/user_guide/tutorials/custom_robots.html) is not executable.

**Comment by StoneT2000** [comment]
There is a typo here, if you follow the tutorial you should have a test.py file. To run get rid of the -m. Should fix it

**Comment by BXZZcj** [comment]
> There is a typo here, if you follow the tutorial you should have a test.py file. To run get rid of the -m. Should fix it

Thank you for your reply.

I have followed the tutorial and obtained the `test.py` file. The issue doesn't seem to be with the `-m` option. Instead, it seems to lie in a mismatch between the desired action space dimension and the provided one. 

Specifically, the controller appears to expect a one-dimensional action space for the gripper, but the provided action space is two-dimensional because the gripper has two movable joints.

Here's the error message:

The error information is as follows:
```
Selected Robot has the following keyframes to view: 
dict_keys(['rest'])
Traceback (most recent call last):
  File "/home/jiechu/miniconda3/envs/roboSim/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jiechu/miniconda3/envs/roboSim/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/jiechu/miniconda3/envs/roboSim/lib/python3.9/site-packages/mani_skill/examples/test.py", line 5, in <module>
    demo_robot_script.main()
  File "/home/jiechu/miniconda3/envs/roboSim/lib/python3.9/site-packages/mani_skill/examples/demo_robot.py", line 74, in main
    env.step(kf.qpos)
  File "/home/jiechu/miniconda3/envs/roboSim/lib/python3.9/site-packages/mani_skill/envs/sapien_env.py", line 768, in step
    action = self._step_action(action)
  File "/home/jiechu/miniconda3/envs/roboSim/lib/python3.9/site-packages/mani_skill/envs/sapien_env.py", line 828, in _step_action
    self.agent.set_action(action)
  File "/home/jiechu/miniconda3/envs/roboSim/lib/python3.9/site-packages/mani_skill/agents/base_agent.py", line 255, in set_action
    self.controller.set_action(action)
  File "/home/jiechu/miniconda3/envs/roboSim/lib/python3.9/site-packages/mani_skill/agents/controllers/base_controller.py", line 271, in set_action
    assert action.shape == (self.scene.num_envs, action_dim), (
AssertionError: (torch.Size([9]), 8)
```

However, when I switch the gripper controller configured in `my_panda.py` from `PDJointPosMimicControllerConfig` (which is recommended by the tutorial) to `PDJointPosControllerConfig`, the error disappears.

Sorry to bother you.

**Comment by StoneT2000** [comment]
This is intentional. Typically grippers are mimic joints, where there is a constraint on the joint angle to be the same. For Panda the implementation we provide uses mimic joint controller so there is one less degree of freedom. If you  don't use the mimic joint controller config and use the normal pd joint position one then you can control both gripper joints

I will probably need to change the tutorial a little bit since the keyframe action tries to set the angle for both gripper joints probably.

**Comment by StoneT2000** [comment]
ok this has been fixed now. The demo robot code (test.py) will now handle situations where a robot might have multiple joints constrained against each other and still accept an action that applies a qpos to every joint. To try it out you can install directly from github or you can wait for the next pypi release.

**Comment by BXZZcj** [comment]
> ok this has been fixed now. The demo robot code (test.py) will now handle situations where a robot might have multiple joints constrained against each other and still accept an action that applies a qpos to every joint. To try it out you can install directly from github or you can wait for the next pypi release.

Thank you for your attention.
