### ISSUE TITLE
Documentation and code are inconsistent

### ISSUE THREAD

**Issue by XiaohanLei** [haosulab/ManiSkill#325]
Hi!

Thanks for your team's great work!

I read your docs carefully and see for tasks like, "StackCube-v1", "PickSingleYCB-v1", etc., do support xarm. However, when I run the code  like 
    env = gym.make(
        "PickSingleYCB-v1",
        obs_mode="state",
        robot_uids="xarm",
        num_envs=16
    )
   it still keeps saying the robot is not supported.
   So, how can I use xarm for these tasks?
   Thanks in advance.

**Comment by StoneT2000** [comment]
Looks like we need to add back the xarm in to those tasks as supported. If I recall correctly we needed to fix some parts of the xarm. We will get this fixed soon
