### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by RussRobin** [haosulab/ManiSkill#330]
Hi,

I'm using RGBD mode to get rgb and depth observations, and resolution for images are 128*128. Is it possible to customize image resoultions and set them to, e.g. 256*256?

Regards

**Comment by StoneT2000** [comment]
An example of this done is https://github.com/haosulab/ManiSkill/blob/main/mani_skill/examples/demo_vis_rgbd.py

Essentially you just need to pass in a `sensor_configs` argument to the gym.make function. You can set global overrides for sensors there and also camera specific ones as well.

```python
sensor_configs = dict(width=256, height=256)
env = gym.make("PickCube-v1", sensor_configs=sensor_configs)
```

**Comment by RussRobin** [comment]
Thanks for your reply. I am also a bit confused about the coordinate system in ManiSkill. Based on the RGB videos and the videos observed in RTX-ManiSkill, it seems to me that the x-axis is perpendicular to the screen and pointing inward, the y-axis is pointing to the right, and the z-axis is pointing upwards. This appears to be a left-handed coordinate system. Is that correct?

**Comment by StoneT2000** [comment]
This depends on where the camera is positioned. In the world frame the z axis is always whatever is canonically up/down (direction of gravity) and the x/y axis are the other 2 perpendicular to the r z axis.

If a camera is rotated around the z axis 90 degrees, x and y would "flip"

**Comment by RussRobin** [comment]
Thank you for your reply. I tried it out but got an error:

My code:
```
sensor_configs = dict(width=256, height=256) # 设置camera_image的图像大小
    env = gym.make(
        "PlugCharger-v0", 
        obs_mode="rgbd", 
        control_mode="pd_ee_delta_pose", 
        render_mode="human",
        sensor_configs=sensor_configs
    )
```


Error:
```
Traceback (most recent call last):
  File "anaconda3/envs/maniskill/lib/python3.9/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "anaconda3/envs/maniskill/lib/python3.9/site-packages/mani_skill2/utils/registration.py", line 92, in make
    env = env_spec.make(**kwargs)
  File "anaconda3/envs/maniskill/lib/python3.9/site-packages/mani_skill2/utils/registration.py", line 34, in make
    return self.cls(**_kwargs)
  File "anaconda3/envs/maniskill/lib/python3.9/site-packages/mani_skill2/envs/assembly/base_env.py", line 28, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'sensor_configs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try_maniskill_ctrl.py", line 146, in run_maniskill
    env = gym.make(
  File "anaconda3/envs/maniskill/lib/python3.9/site-packages/gymnasium/envs/registration.py", line 814, in make
    raise type(e)(
TypeError: __init__() got an unexpected keyword argument 'sensor_configs' was raised from the environment creator for PlugCharger-v0 with kwargs ({'obs_mode': 'rgbd', 'control_mode': 'pd_ee_delta_pose', 'render_mode': 'human', 'sensor_configs': {'width': 256, 'height': 256}})
```

**Comment by StoneT2000** [comment]
Apologies it should be `sensor_cfgs` as the argument, not `sensor_configs`.

```python
sensor_cfgs = dict(width=256, height=256)
env = gym.make("PickCube-v1", sensor_cfgs=sensor_cfgs)
```

**Comment by StoneT2000** [comment]
What version of ManiSkill are you using? It looks like you are using the old maniskill v2. We recommend to upgrade to maniskill v3 which has most of the same tasks like plug charger and runs faster via gpu sim. See the readme in https://github.com/haosulab/ManiSkill

If you want to do it for maniskill v2 then `sensor_configs` should be called `camera_cfgs` instead. https://github.com/haosulab/ManiSkill/blob/v0.5.3/mani_skill2/envs/sapien_env.py#L93C9-L93C20

**Comment by RussRobin** [comment]
Thanks for your reply!
Yes I’m using maniskill2. I’m wondering which version should I use to keep everything the same with maniskill rtx version?

**Comment by RussRobin** [comment]
Also, I find the coordinates a lot bit confused to me. I’ m using pd_ee_delta_pose, with action[2]>0 to go along z axis.
It seems that the z axis points downwards, which is still different from rtx.

**Comment by StoneT2000** [comment]
That seems like a bug, I'll have to check.

To install the latest maniskill, you just pip install mani_skill and verify its version starts with v3.0.x

You can then pip uninstall mani_skill2 which was the old package

**Comment by RussRobin** [comment]
Thanks! I confirm that in maniskill 2, the z axis points downwards. Here's my code:
```
env = gym.make(
        "PickSingleYCB-v0", 
        obs_mode="rgbd", 
        control_mode="pd_ee_delta_pose", 
        render_mode="human",
    )

done = False
while not done:
    action = np.array([0,0,0.02,0,0,0,0])
    obs, _, terminated, truncated, _ = env.step(action)
    env.render() 
```

**Comment by StoneT2000** [comment]
I can confirm it happens. In fact for ManiSkill 3, the CPU sim has this bug where z-action > 0 makes it go down while on GPU sim it does not have this issue. In fact it seems the position is all reversed in cpu sim. Fixing it now.

**Comment by StoneT2000** [comment]
After some further discussion I think our team will do a overhaul of how EE-based controllers work since there are a lot of options and choices of how to control the end-effector. The current default is actually correct but not that intuitive and not explained well in the documentation. The reason why the z-action is "reversed" is because the delta translation in your action is taken relative to the end-effector frame's orientation. For example if the end-effector is rotated/tilted in some way, -z or +z will not be in the root link's or world frame, but it is the end-effector frame.

Anyway I will update here once I finish up some cleaner documentation around how this work and what options of EE-control you can choose from (there are many variations actually, some of which are commonly used with real robots than others).

**Comment by RussRobin** [comment]
Great! Millions of thanks to you and your team!

BTW, is there any easy ways for me to make the control mode, action space, etc. the same with ManiSkill RTX version?

Thanks a lot.

**Comment by StoneT2000** [comment]
Instructions with visual guides about end-effector control updated here: https://maniskill.readthedocs.io/en/latest/user_guide/concepts/controllers.html#pd-ee-end-effector-pose

Note that the default pd_ee_delta_pose control on the CPU sim for ManiSkill3 is a little bit different than before. It is now the "intuitive one" namely in the frame of the robot base (so +z actually means +z).

If you want to experiment with other controllers you can inherit the Panda class / directly edit it if you work with ManiSkill from source and update the controller configs (e.g. change the frame).

The code changes made for this overhaul is currently on the main branch (install from source to use it).

**Comment by RussRobin** [comment]
Great thanks! I ll close the issue.
