### ISSUE TITLE
RuntimeError: createInstance: No Vulkan extensions found for window surface creation (hint: set VK_ICD_FILENAMES to `locate icd.json`)

### ISSUE THREAD

**Issue by kkk123serendipity** [haosulab/ManiSkill#34]
I think I followed the instructions in the github page step by step but encounter this problem. Is there any way to solve the problem? Sorry that I'm new to Vulkan.

**Comment by fbxiang** [comment]
Maybe you can show us the results of `nvidia-smi` and `ls /usr/share/vulkan/icd.d` to help identify the issue. If `nvidia_icd.json` is not in `/usr/share/vulkan/icd.d` directory, you should probably try to reinstall your NVIDIA driver.
You can also try to install the `vulkan-utils` package (assuming Ubuntu) and show us the output of `vulkaninfo`. 
You can also try their minimal example `vkcube`. If it fails to run, you can probably search the error message and find a solution, which will probably also resolve the issue in ManiSkill.
