### ISSUE TITLE
Only 2 tasks available when downloading demonstrations

### ISSUE THREAD

**Issue by YY-GX** [haosulab/ManiSkill#342]
Hi all, when I use `python -m mani_skill.utils.download_demo` to check what packages I could download, there're only 2:
```shell
Available dataset UIDs:
['PickCube-v1', 'StackCube-v1']
``` 
The size of them are very small as well:
```shell
480K	PickCube-v1
600K	StackCube-v1
```
Could you please help me with this? It's really appreciated!!

**Comment by StoneT2000** [comment]
I can upload more demonstrations later. At the moment the two you downloaded are the human teleoperated datasets (hence small size)

Last time we had motion planning generatable datasets which can be generated following this documentation: https://maniskill.readthedocs.io/en/latest/user_guide/data_collection/motionplanning.html

I will upload a downloadable result of the demo generation scripts in the future as well as RL generated demos for some tasks

**Comment by StoneT2000** [comment]
One reason I have not yet uploaded all demo datasets is because we are still discussing how to best parametrize environment state when  objects in the environment may have different geometries and are seed dependent.

**Comment by StoneT2000** [comment]
Hi @YY-GX I have uploaded more demonstrations, some created via different sources (motion planning, teleop guided motion planning by human, RL/neural network generated). There are now 5 tasks available for download (PushCube, PickCube, StackCube, PlugCharger, PegInsertionSide) if you use the main code branch. Alternatively you can download them straight from hugging face https://huggingface.co/collections/haosulab/maniskill-demonstration-datasets-66565c3c37a090c729dbdb16

Teleop demos tend to be very small (although they are actually enough to solve the task if a good algorithm is used). Motion planned and RL generated tend to have about 1000 demos (most of which are successful). RL generated demos usually are the easiest to learn from.
