### ISSUE TITLE
Fix replay tool for converting pd_joint_pos to pd_ee_delta_pos/pose control

### ISSUE THREAD

**Issue by StoneT2000** [haosulab/ManiSkill#346]

**Comment by sean1295** [comment]
Hello, thank you so much for your contribution to making this amazing environment available! I am curious if you have had any time to fix the replay trajectory code. I am trying to do imitation learning with motion planned trajectories but it looks like transforming it into eef control is impossible. Thanks in advance.

**Comment by StoneT2000** [comment]
yeah this is on my TODO list at the moment. Will bump up the priority to try and fix it earlier

**Comment by StoneT2000** [comment]
@sean1295 should be mostly fixed now. For less precise tasks like PickCube, the success rate of conversion to pd_ee_delta_pos/pose is near 100%. For highly precise tasks like PegInsertion and PlugCharger it is lower. 

We used to have very high conversion success rate for those two tasks but not sure why it dropped so much. We are still investigating that.
