### ISSUE TITLE
gravity in pinch_env

### ISSUE THREAD

**Issue by hongkai-dai** [haosulab/ManiSkill#35]
The mpm model gravity is (0, 0, -1) in the pinch environment https://github.com/haosulab/ManiSkill2/blob/0f72be61a866752609039b1e797403d10c29e42b/mani_skill2/envs/mpm/pinch_env.py#L59, may I ask why it is not set to -9.8 as in the original MPMModel https://github.com/haosulab/ManiSkill2/blob/0f72be61a866752609039b1e797403d10c29e42b/warp_maniskill/warp/sim/model.py#L357?

**Comment by fbxiang** [comment]
This design is mainly for simulation stability. We find a stable simulation of the material with a normal gravity would require a much smaller time step, making the simulation much slower. We tune the gravity to be smaller similar to other frameworks like PlasticineLab.

**Comment by hongkai-dai** [comment]
I see, thanks a lot for the prompt reply! That makes sense.
