### ISSUE TITLE
Issue with running ppo

### ISSUE THREAD

**Issue by szczekulskij** [haosulab/ManiSkill#364]
Hi, 
I'm a CSE276F student.
I'm trying to run ppo via 1quick_start notebook: https://colab.research.google.com/github/haosulab/ManiSkill/blob/main/examples/tutorials/1_quickstart.ipynb#scrollTo=Pm8hUvdYbWgH

When running below lines on Collab T4 machine:
```
!python ppo.py --env_id="PushCube-v1" --exp-name="state-pushcube" \
  --num_envs=1024 --update_epochs=8 --num_minibatches=32 \
  --total_timesteps=600_000 --eval_freq=8 --num-steps=20
  ```

I keep on getting the following error:
<img width="925" alt="image" src="https://github.com/haosulab/ManiSkill/assets/24961619/706f3e3c-3c1b-4b93-9b30-9f12cd3c36fd">

Could I request help please ?

**Comment by StoneT2000** [comment]
I have an idea of what the bug is (it might only appear in Colab and is caused by maybe gc.collect unloading modules) but this is actually fine. Your final model is saved still and the code ran to completion.
