### ISSUE TITLE
How to define a new material?

### ISSUE THREAD

**Issue by DevinJoeUU** [haosulab/ManiSkill#397]
I used the following code to define a new material in Mani-Skill2 before:
```
renderer = sapien.SapienRenderer()
material = renderer.create_material()
material.set_diffuse_texture_from_file(wall['material_path'])
```
But in maniskill3, it seems that the "set_diffuse_texture_from_file" is deleted. I find that all functions like "set**from_file" is deleted in sapien3's RenderMaterial class.

**Comment by StoneT2000** [comment]
You can set them like python properties now usually

```
from sapien.render import RenderMaterial, RenderTexture2D
material = RenderMaterial()
material.diffuse_texture = RenderTexture2D(wall['material_path'])
```

`renderer.create_material` is no longer recommended to be used as well. Just create the RenderMaterial object directly.

If you have typehints you can check what you can set.
