### ISSUE TITLE
Does maniskill3's renderer support remote window display

### ISSUE THREAD

**Issue by DevinJoeUU** [haosulab/ManiSkill#402]
I install maniskill3 in a remote linux server, and run the example environment ReplicaCAD using the following code:
```
python -m mani_skill.examples.demo_random_action -e "ReplicaCAD_SceneManipulation-v1" --render-mode="human" --shader="rt-fast"
```
It reports the following error:
```
self.window = RenderWindow(*resolution, self.shader_dir)
RuntimeError: Create window failed: Renderer does not support display.
```
I checked the vulkaninfo and its output information is normal.

**Comment by StoneT2000** [comment]
There may be a solution using x-forwarding or VNC but it probably will not work / be very slow unfortunately.

**Comment by lozoRUST** [comment]
> 我在远程 linux 服务器中安装 maniskill3，并使用以下代码运行示例环境 ReplicaCAD：
> 
> ```
> python -m mani_skill.examples.demo_random_action -e "ReplicaCAD_SceneManipulation-v1" --render-mode="human" --shader="rt-fast"
> ```
> 
> 它报告以下错误：
> 
> ```
> self.window = RenderWindow(*resolution, self.shader_dir)
> RuntimeError: Create window failed: Renderer does not support display.
> ```
> 
> 我检查了 vulkaninfo，它的输出信息是正常的。

I‘ve comed accross the same problem. Have you found the solution?

**Comment by StoneT2000** [comment]
@lozoRUST Do you have a display monitor? You must use a display monitor to view the UI

**Comment by lozoRUST** [comment]
@StoneT2000 Thanks for reply! Yes, i've tried xfec and saw the desktop on VNC succefully. But the terminal still domonstrated the same RuntimeError: Create window failed: Renderer does not support display.

**Comment by yizt** [comment]
> @StoneT2000 Thanks for reply! Yes, i've tried xfec and saw the desktop on VNC succefully. But the terminal still domonstrated the same RuntimeError: Create window failed: Renderer does not support display.

I met the same problem using VNC,did you solve it?

**Comment by junjzhang** [comment]
Hi, I've met the same issue and I solved by using turbovnc + virutalGL.

**Comment by SoshinK** [comment]
I try to use turbovnc + virutalGL, but have the following error:

```
RuntimeError: vk::Device::createSwapchainKHRUnique: ErrorOutOfDeviceMemory
```

I think it can be also related to https://github.com/haosulab/ManiSkill/issues/680
