### ISSUE TITLE
Install of ManiSkill2 fails

### ISSUE THREAD

**Issue by caiqi** [haosulab/ManiSkill#41]
Thanks for open-sourcing the awesome work. I have trouble installing ManiSkill2 on a server and hope you can provide some help. Thanks. 

1. I am using a training platform so I can only run commands inside the docker container. The NVIDIA driver version is 470.57.02. I could not change the version of the NVIDIA driver due to platform limitations. There is no libGLX_nvidia.so file inside the docker. So I download the NVIDIA driver 470.57.02 from the official [website](https://www.nvidia.com/Download/driverResults.aspx/177145/en-us/) and extract all files from the driver file. I find libGLX_nvidia.so.470.57.02 and nvidia_icd.json and save them to /dev/shm/base folder. 
![image](https://user-images.githubusercontent.com/8349599/204587730-b1cd32a5-07ab-4343-80d1-e596b328a900.png)
![image](https://user-images.githubusercontent.com/8349599/204588129-553deb3f-a3a0-4f80-ba20-1c6f35735dc2.png)

I also find the vulkan libs:
![image](https://user-images.githubusercontent.com/8349599/204588412-ae3d474b-0769-4915-83f4-645a39642828.png)

2. The command I run is: 
![image](https://user-images.githubusercontent.com/8349599/204587600-f3fb3047-81cc-44b3-ae6c-8850e7ecfda6.png)

It seems there is something wrong with the render. Could you please give me some hints how to solve this problem?

**Comment by Jiayuan-Gu** [comment]
Hi, could you first try the method described in #34 to verify your Vulkan installation? Besides, are you able to use a different docker image to verify whether it is an issue due to the docker configuration? We provide an example [docker file](https://github.com/haosulab/ManiSkill2/blob/main/docker/Dockerfile) and a built docker image (haosulab/maniskill2022-challenge:latest).

**Comment by caiqi** [comment]
1. The information of nvidia-smi and vulkaninfo is : 
![image](https://user-images.githubusercontent.com/8349599/204708915-ec838686-fd66-48fd-b4ee-13032f4e4009.png)
2. I follow the docker file to add libvulkan1 and mesa-utils into my current container, the problem still exist. 
3. I try to pull haosulab/maniskill2022-challenge:latest from the docker hub and find that there is also no libGLX_nvidia.so file inside the container, is this normal or I should use some specific command to start the container?

**Comment by fbxiang** [comment]
Based on the information you provided, my suggestion is to fix the NVIDIA driver installation on the **host** machine. I have not seen a case where unpacking a downloaded NVIDIA driver could "fix" a faulty installation. I suggest only using ways supported by NVIDIA to install their driver (run file or through package manager) on the **host** machine.

`libGLX_nvidia.so` missing in the container is more or less expected. When you pass `--gpus all` to a docker command, the graphics driver, including all the `/usr/lib/**nvidia**.so` and other related files are mapped to the container. So if those files are missing in the host, you will not get them in the container, and manually copying them into the container probably will not help.

So I believe vulkaninfo is giving you the correct message that you have an incompatible driver on the host machine. The host driver essentially decides to disable graphics capability of your GPU.

**Comment by caiqi** [comment]
Thanks for your timely reply! Currently, the host machine is a cloud cluster so I have to find another workaround.  "The host driver essentially decides to disable graphics capability of your GPU." Do you mean that the host driver can disable graphics capability so that I can normally use CUDA/PyTorch inside the container but could not use vulkan or sapien?

**Comment by fbxiang** [comment]
Yes, libGLX implements many graphics features, including OpenGL and Vulkan. CUDA applications (e.g. pytorch) are not affected. Your host driver does not have graphics support and the only solution I know is to (maybe convince the admin and) do a full installation of the NVIDIA driver. If you find some other workaround, please do let us know, as it is an issue that happens quite often to people wanting to run graphics applications on cloud servers without graphics libraries.

**Comment by caiqi** [comment]
Thanks!
