### ISSUE TITLE
How to get camera extrinsic and intrinsic parameter?

### ISSUE THREAD

**Issue by oym1994** [haosulab/ManiSkill#417]
Hi, thanks for your great job. I want to use this data to train a 3D policy where camera intrinsic and extrinsic parameter are needed but unfortunately I cant see this information in the raw data. So can you provide this information or tell how to get these？

Thanks for your attention and wait for your kind response!

**Comment by StoneT2000** [comment]
It should in the observations by default. I think it is in obs["sensor_params"]["camera_name"]. Make sure `obs_mode="rgbd"` or one of the visual modes.

**Comment by oym1994** [comment]
> It should in the observations by default. I think it is in obs["sensor_params"]["camera_name"]. Make sure `obs_mode="rgbd"` or one of the visual modes.

Thank you! I will try .

**Comment by StoneT2000** [comment]
@oym1994 has your issue been resolved?

**Comment by StoneT2000** [comment]
Closing the issue now as it has become stale.
