### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by baiyu858** [haosulab/ManiSkill#426]
`python -m mani_skill.examples.demo_random_action -e PickCube-v1`
output:
`opts: []
env_kwargs: {}
Segmentation fault (core dumped)
`
GPU:RTX 3090
How can I solve this problem? Thank you for your reply!

**Comment by StoneT2000** [comment]
Can you share the result of nvidia-smi, pip list, and what linux system you are on?

**Comment by baiyu858** [comment]
> Can you share the result of nvidia-smi, pip list, and what linux system you are on?


Thank you for your reply.
I had this problem at the beginning of the step, I don't know what is the reason? mani-skill2 has the same problem.
I'm using Ubuntu 20.04 LTS on the server side (GNU/Linux 5.4.0-174-generic x86_64).
`nvidia-smi:`    

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:1A:00.0 Off |                  N/A |
| 30%   31C    P8             31W /  350W |      14MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        Off |   00000000:1B:00.0 Off |                  N/A |
| 30%   30C    P8             20W /  350W |      14MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 3090        Off |   00000000:3D:00.0 Off |                  N/A |
| 30%   27C    P8             18W /  350W |      14MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce RTX 3090        Off |   00000000:3E:00.0 Off |                  N/A |
| 30%   29C    P8             21W /  350W |      14MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA GeForce RTX 3090        Off |   00000000:88:00.0 Off |                  N/A |
| 65%   58C    P2            229W /  350W |   15461MiB /  24576MiB |    100%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA GeForce RTX 3090        Off |   00000000:89:00.0 Off |                  N/A |
|  0%   52C    P2            226W /  350W |   15939MiB /  24576MiB |    100%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA GeForce RTX 3090        Off |   00000000:B1:00.0 Off |                  N/A |
| 51%   52C    P2            229W /  350W |   16203MiB /  24576MiB |    100%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA GeForce RTX 3090        Off |   00000000:B2:00.0 Off |                  N/A |
| 52%   51C    P2            230W /  350W |   15839MiB /  24576MiB |     89%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A   3955805      G   /usr/lib/xorg/Xorg                              8MiB |
|    1   N/A  N/A   3955805      G   /usr/lib/xorg/Xorg                              8MiB |
|    2   N/A  N/A   3955805      G   /usr/lib/xorg/Xorg                              8MiB |
|    3   N/A  N/A   3955805      G   /usr/lib/xorg/Xorg                              8MiB |
|    4   N/A  N/A   1900905      C   ...gzhou/anaconda3/envs/tc2/bin/python       6584MiB |
|    4   N/A  N/A   2032157      C   ...gzhou/anaconda3/envs/tc2/bin/python       8850MiB |
|    4   N/A  N/A   3955805      G   /usr/lib/xorg/Xorg                              8MiB |
|    5   N/A  N/A   1900906      C   ...gzhou/anaconda3/envs/tc2/bin/python       6550MiB |
|    5   N/A  N/A   2032158      C   ...gzhou/anaconda3/envs/tc2/bin/python       9362MiB |
|    5   N/A  N/A   3955805      G   /usr/lib/xorg/Xorg                              8MiB |
|    6   N/A  N/A   1900907      C   ...gzhou/anaconda3/envs/tc2/bin/python       6982MiB |
|    6   N/A  N/A   2032159      C   ...gzhou/anaconda3/envs/tc2/bin/python       9194MiB |
|    6   N/A  N/A   3955805      G   /usr/lib/xorg/Xorg                              8MiB |
|    7   N/A  N/A   1900908      C   ...gzhou/anaconda3/envs/tc2/bin/python       6758MiB |
|    7   N/A  N/A   2032160      C   ...gzhou/anaconda3/envs/tc2/bin/python       9054MiB |
|    7   N/A  N/A   3955805      G   /usr/lib/xorg/Xorg                              8MiB |
+-----------------------------------------------------------------------------------------+
`pip list 
`
Package                  Version
asttokens                2.4.1
certifi                  2024.7.4
charset-normalizer       3.3.2
cloudpickle              3.0.0
contourpy                1.2.1
cycler                   0.12.1
dacite                   1.8.1
decorator                5.1.1
docstring_parser         0.16
eval_type_backport       0.2.0
exceptiongroup           1.2.2
executing                2.0.1
Farama-Notifications     0.0.4
fast_kinematics          0.2.2
filelock                 3.15.4
fonttools                4.53.1
fsspec                   2024.6.1
gitdb                    4.0.11
GitPython                3.1.43
gymnasium                0.29.1
h5py                     3.11.0
huggingface-hub          0.23.5
idna                     3.7
imageio                  2.34.2
imageio-ffmpeg           0.5.1
importlib_metadata       8.0.0
importlib_resources      6.4.0
ipython                  8.18.1
jedi                     0.19.1
Jinja2                   3.1.4
kiwisolver               1.4.5
lxml                     5.2.2
mani_skill               3.0.0b5
markdown-it-py           3.0.0
MarkupSafe               2.1.5
matplotlib               3.9.1
matplotlib-inline        0.1.7
mdurl                    0.1.2
mplib                    0.1.1
mpmath                   1.3.0
networkx                 3.2.1
numpy                    2.0.0
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.5.82
nvidia-nvtx-cu12         12.1.105
opencv-python            4.10.0.84
packaging                24.1
parso                    0.8.4
pexpect                  4.9.0
pillow                   10.4.0
pip                      24.0
prompt_toolkit           3.0.47
psutil                   6.0.0
ptyprocess               0.7.0
pure-eval                0.2.2
Pygments                 2.18.0
pyparsing                3.1.2
pyperclip                1.9.0
python-dateutil          2.9.0.post0
PyYAML                   6.0.1
requests                 2.32.3
rich                     13.7.1
Rtree                    1.3.0
sapien                   3.0.0b1
scipy                    1.13.1
setuptools               69.5.1
shtab                    1.7.1
six                      1.16.0
smmap                    5.0.1
stack-data               0.6.3
sympy                    1.13.0
tabulate                 0.9.0
toppra                   0.6.0
torch                    2.3.1
torchaudio               2.3.1
torchvision              0.18.1
tqdm                     4.66.4
traitlets                5.14.3
transforms3d             0.4.2
trimesh                  4.4.3
triton                   2.3.1
typing_extensions        4.12.2
tyro                     0.8.5
urllib3                  2.2.2
wcwidth                  0.2.13
wheel                    0.43.0
zipp                     3.19.2

**Comment by StoneT2000** [comment]
I hope the bug is not related to having 8 connected GPUs (we have not tested on such a setup before). 

A few possible ideas:
- Install a older version of numpy (1.26.4 works)
- Install a older version of torch (2.2.1 works)

Just realized with the new numpy release I need to pin our numpy dependency to <2.0.0 probably.

If the two other installs do not fix it, there may be a chance your nvidia driver is too new (550). 535.183.01 and cuda version 12.2 is what I run now (535.X should work). You can try downgrading the driver (if you use apt, make sure you install nvidia-driver-xxx without the word server or headless in its name).

Can you also run `ldconfig -p | grep libGLX_nvidia`?

**Comment by baiyu858** [comment]
Thank you for your reply.

`ldconfig -p | grep libGLX_nvidia`
output:
libGLX_nvidia.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGLX_nvidia.so.0

I tried to lower the numpy and torch versions, but it didn't work, it was still a Segmentation fault (core dumped). Has anyone else had this problem? I was afraid to drop the driver version because others were sharing the server. What is the fault caused by this [Segmentation fault (core dumped)], which is strange 🤨, and nothing else is reported?

**Comment by StoneT2000** [comment]
@fbxiang any idea? The driver version is very new and I have not used it before so I suspect it might be that.

**Comment by StoneT2000** [comment]
Actually @baiyu858 can you run

```
python -m sapien.example.hello_world
```

**Comment by baiyu858** [comment]
> Actually @baiyu858 can you run 你能跑吗?
> 
> ```
> python -m sapien.example.hello_world
> ```

`python -m sapien.example.hello_world`
output:
Segmentation fault (core dumped)

**Comment by StoneT2000** [comment]
Another option is to try and pull the docker image and run the example code from there? You will need to setup nvidia docker containers if you haven't done so before. https://maniskill.readthedocs.io/en/latest/user_guide/getting_started/docker.html

Based on your packages and nvidia-smi its not obvious to me just yet what might be causing this. Confirmed with @fbxiang earlier that your driver version is not an issue (although you can try upgrading to latest if you haven't already, @fbxiang is using the latest driver right now)

**Comment by tongzhoumu** [comment]
@baiyu858 try to downgrade your numpy to 1.26

**Comment by fbxiang** [comment]
> @baiyu858 try to downgrade your numpy to 1.26

This makes a lot of sense.

**Comment by StoneT2000** [comment]
I asked the user to downgrade numpy earlier to 1.26.4 but they said it did not work

**Comment by baiyu858** [comment]
@StoneT2000 
I suspect there may be a problem with vulkan because the output result has a `Segmentation fault (core dumped)` on the last line.

`  vulkaninfo`
output:
........(Leave out a lot)
        VK_KHR_multiview                      : extension revision 1
        VK_KHR_push_descriptor                : extension revision 2
        VK_KHR_relaxed_block_layout           : extension revision 1
        VK_KHR_sampler_mirror_clamp_to_edge   : extension revision 3
        VK_KHR_separate_depth_stencil_layouts : extension revision 1
        VK_KHR_shader_atomic_int64            : extension revision 1
        VK_KHR_shader_draw_parameters         : extension revision 1
        VK_KHR_storage_buffer_storage_class   : extension revision 1
        VK_KHR_swapchain                      : extension revision 70
        VK_KHR_uniform_buffer_standard_layout : extension revision 1
        VK_KHR_variable_pointers              : extension revision 1

VkQueueFamilyProperties:
= = = = = = = = = = = = = = = = = = = == = =
Segmentation fault (core dumped)

**Comment by StoneT2000** [comment]
try reinstalling vulcan, and also follow the vulcan trouble shooting guide on our docs (make sure those icd files are there)

**Comment by StoneT2000** [comment]
Closing the issue as it is stale

**Comment by lieyanzhan** [comment]
> Actually [@baiyu858](https://github.com/baiyu858) can you run
> 
> ```
> python -m sapien.example.hello_world
> ```



> Can you share the result of nvidia-smi, pip list, and what linux system you are on?

<img width="1494" height="754" alt="Image" src="https://github.com/user-attachments/assets/d400f9f5-388d-421d-ab6a-a43998d1710b" />
l  have the same problem,  and I run the maniskill in the docker, how can l fix this problem?
