### ISSUE TITLE
Can I scale a loaded actor without changing its shape?

### ISSUE THREAD

**Issue by DevinJoeUU** [haosulab/ManiSkill#427]
I use the following code to load a sofa, but it seems that the shape is changed. The first picture is loaded without `scale` parameter. And the second is loaded with `scale` parameter.
```
builder = self.scene.create_actor_builder()
scale = np.array([3.0069477324372293, 2.1716842013819684, 0.7398047878686137])
# builder.add_visual_from_file(file_path, scale=scale)
# builder.add_multiple_convex_collisions_from_file(file_path, scale=scale, decomposition="cocad")
builder.add_visual_from_file(file_path)
builder.add_multiple_convex_collisions_from_file(file_path, decomposition="cocad")
builder.initial_pose = sapien.Pose([0, 0, 3], [0.707, 0.707, 0, 0])
builder.set_scene_idxs([0])
actor = builder.build_static(name="test")
mesh = actor.get_first_collision_mesh()
real_pos = actor.pose.p
min_bbox, max_bbox = mesh.bounds
size = max_bbox - min_bbox
center = (min_bbox + max_bbox) / 2
print(f"position:{real_pos}")
print(f"min_bbox: {min_bbox}")
print(f"max_bbox: {max_bbox}")
print(f"size: {size}")
print(f"center: {center}")
print(f"position - center: {np.array(real_pos) - np.array(center)}")
```
Its output is below:
```
position:tensor([[0., 0., 3.]])
min_bbox: [-0.607 -0.737  2.806]
max_bbox: [0.698 0.2   3.12 ]
size: [1.305 0.937 0.314]
center: [ 0.046 -0.269  2.963]
position - center: [[-0.046  0.269  0.037]]
```
![Snipaste_2024-07-16_21-53-05](https://github.com/user-attachments/assets/3e21eb02-fe31-4a0e-a30a-7cae06ab881e)
![Snipaste_2024-07-16_21-47-22](https://github.com/user-attachments/assets/c5c9c958-dd08-477b-af94-99403b421207)

**Comment by StoneT2000** [comment]
Can you share the sofa mesh files? I'll see if i can reproduce the bug

**Comment by DevinJoeUU** [comment]
I'm sorry for that the file is too big to be uploaded directly. You can download it using the following code:
```
import objaverse
objs = objaverse.load_objects(uids=["493cf761ada14c0bbc1f5b71369d8d93"])
file_path = objs["493cf761ada14c0bbc1f5b71369d8d93"]
```
Or you can download it from the link below directly.
[https://huggingface.co/datasets/allenai/objaverse/resolve/main/glbs/000-120/493cf761ada14c0bbc1f5b71369d8d93.glb?download=true](url)

**Comment by DevinJoeUU** [comment]
I have known that why its shape changed. If I use `scale = np.array([2.3, 2.3, 2.3])`, its would sacle up and the shape wouldn't change. I'm sorry for that I misunderstood the usage of `scale`. I previously thought it represented the absolute length of the width, height, and depth.
