### ISSUE TITLE
Robot control in ArchitecTHOR_SceneManipulation-v1

### ISSUE THREAD

**Issue by fujiawei0724** [haosulab/ManiSkill#434]
Thanks for the great platform, and you have solved lots of problems for me, thanks for the patient help. 

In ArchitecTHOR_SceneManipulation-v1, is there a way to quickly control the robot so that it can move to a specified location or grab an object at a specified location?

Looking forward to your reply. Thanks again.

**Comment by StoneT2000** [comment]
That's a pretty hard problem! We are currently working a RL approach to learn contact rich long horizon manipulation but it's not trivial.

We will eventually integrate some teleoperation solutions but they aren't a priority at this moment.

**Comment by fujiawei0724** [comment]
Thanks for your answering. Another question is that in the ArchitecTHOR_SceneManipulation-v1, how to get the pose of the robot in the scene? When I try to use self.robot.get_pose(), it seems the value is invalid, since when the robot is moving in the scene, self.robot.get_pose() always return a static array. Looking forward to your reply.

**Comment by StoneT2000** [comment]
Ah this is due to how free joints / mobile bases are modeled in simulation. Mobile bases are modeled by three joints, X, Y prismatic and a resolute joint along the z axis. So the first 3 qpos values of the robot give you the x, y position and z axis rotation of the robot relative to the pose.

**Comment by fujiawei0724** [comment]
Thank you very much~
