### ISSUE TITLE
How to use objects from ReplicaCAD and AI2THOR in my custom scenes?

### ISSUE THREAD

**Issue by DingChunQ** [haosulab/ManiSkill#442]
Hello！
I want to use some objects from ReplicaCAD (or AI2THOR) scenes and place them in my own custom scenes, such as the bowls and pans in the photo. How can I extract these objects?
![2ad8a97b57f4cc6426c67845e4d651b](https://github.com/user-attachments/assets/b2a8f891-15ab-4691-bd99-003b8d048221)

Also, where can I easily browse all the objects in all scenes in ReplicaCAD and AI2THOR?

**Comment by StoneT2000** [comment]
These assets are curated by the authors of ReplicaCAD and AI2THOR, we simply just instantiate them here. To find the assets you can go to the folder the assets were downloaded, you can find .glb files that you can copy and build actors/articulations with yourself.

To get the exact ID you may want to copy the scene builder code for these scenes and print each object id built and the file used.
