### ISSUE TITLE
How to Specify the Rendering GPU?

### ISSUE THREAD

**Issue by ShiguangSun** [haosulab/ManiSkill#447]
Hello, I have a question. When running an experiment, I specified a GPU, but I found that the GPU I specified seems to be used only for network computations, while the task rendering GPU is still using GPU 0. Is it possible to specify which GPU is used for task rendering?

**Comment by StoneT2000** [comment]
At the moment, all simulation and rendering occurs on GPU 0 it seems. I will see if we can get this feature added soon

**Comment by ShiguangSun** [comment]
> At the moment, all simulation and rendering occurs on GPU 0 it seems. I will see if we can get this feature added soon

Ok, Thanks for your replay.

**Comment by StoneT2000** [comment]
Hi @ShiguangSun do you have a server which supports multiple GPUs and can help test? I have a fix

**Comment by StoneT2000** [comment]
You can try the latest code by running

```python
pip install --upgrade git+https://github.com/haosulab/ManiSkill.git
```

and then see the new docs on gpu device selection here:
https://maniskill.readthedocs.io/en/latest/user_guide/getting_started/quickstart.html#additional-gpu-simulation-rendering-customization

**Comment by ShiguangSun** [comment]
> You can try the latest code by running
> 
> ```python
> pip install --upgrade git+https://github.com/haosulab/ManiSkill.git
> ```
> 
> and then see the new docs on gpu device selection here: https://maniskill.readthedocs.io/en/latest/user_guide/getting_started/quickstart.html#additional-gpu-simulation-rendering-customization

Ok, I will try it.
