### ISSUE TITLE
How to use ManiSkill2 as a benchmark？

### ISSUE THREAD

**Issue by yingfei1016** [haosulab/ManiSkill#449]
Hello，

I would like to use ManiSkill2 as a benchmark, but **the documentation** has been upgraded to ManiSkill 3.0. I am confused about the use of ManiSkill2, such as how should I **download the data** to align with the previous methods. I see there are multiple versions of the data on Hugging Face, and I am unsure about how to handle the **evaluation**. I hope to maintain consistency with the CVPR workshop！

Thank you very much！

**Comment by StoneT2000** [comment]
ManiSkill 3.0 is still in beta and not completely ready to have an official benchmark. It simply is a massive collection of various tasks but the official benchmark (for RL, IL, etc. areas of research) will pick out a subset of tasks and have baseline results for.

For ManiSkill 2, you can use the original code here: https://github.com/haosulab/ManiSkill/tree/v0.5.3 and follow the old documentation there for how to download demos, assets etc.

By default maniskill 3 demos/data will go to the "~/.maniskill" folder while for ManiSkill 2 it will go elsewhere.

If you want to compare against methods that tested on ManiSkill2, my recommendation now is to still use ManiSkill 2, at least until ManiSkill 3 has its comprehensive baseline results completed.

**Comment by yingfei1016** [comment]
In  https://github.com/haosulab/ManiSkill/tree/v0.5.3，the document has also updated to latest version. 
<img width="744" alt="1721835066872_7AB2FDB0-9F46-4ae5-BBB2-C8FDF42BF8B7" src="https://github.com/user-attachments/assets/e8bf748e-c3e3-491c-989c-73aa55b0ca9c">

Can you send me a old documentation.

**Comment by yingfei1016** [comment]
1、I download the data from https://huggingface.co/datasets/haosulab/ManiSkill2/tree/main/demos/v0/ . However, I find the code in https://github.com/tongzhoumu/ManiSkill_Baselines use a different url path. It is very slow,
<img width="837" alt="1721835293239_73342055-9CB5-43e8-A837-9107571AC2D4" src="https://github.com/user-attachments/assets/4f7173d0-801e-4945-a8a9-14042489c5d5">

If the https://huggingface.co/datasets/haosulab/ManiSkill2/tree/main/demos/v0/ is the right data path?

2、The document in CVPR workshop also expired.
<img width="933" alt="1721835449202_1792C072-DFB7-459d-B3CA-7EF0F1E221E7" src="https://github.com/user-attachments/assets/e24ecb54-ee61-4ebb-a5a7-822a256acb19">

**Comment by StoneT2000** [comment]
Looks like the link is outdated.

This is the docs link for the maniskill 2: https://maniskill.readthedocs.io/en/v0.5.3-rtd/
For envs: https://maniskill.readthedocs.io/en/v0.5.3-rtd/concepts/environments.html

For dataset download, the old urls are the correct ones. The new ones which are mostly hosted on github or hugging face are for maniskill 3. Unfortunately download speed is heavily dependent on your network and our servers and can be variable.

**Comment by yingfei1016** [comment]
Thank you very much! It helps me o lot!
