### ISSUE TITLE
Where is the user_solution.py for the evalution?

### ISSUE THREAD

**Issue by yingfei1016** [haosulab/ManiSkill#457]
Hi,

I following the old document to process the data and train my model. After that I want to test my model locally, but I find the template code (https://github.com/haosulab/ManiSkill2/tree/main/examples/submission) is out-of-date, where can I find this code?

<img width="619" alt="1722088560736_84E2DB92-1F3F-4026-8A4D-51ACE8BAAABE" src="https://github.com/user-attachments/assets/b6204ea0-ed12-44fc-a22a-daeb4941ab27">

**Comment by StoneT2000** [comment]
I think it refers to https://github.com/haosulab/ManiSkill/tree/v0.5.3/mani_skill2/evaluation/solution.py

However this is just for online evaluation, I don't think we are running an online evaluation service anymore.

**Comment by yingfei1016** [comment]
Thank you! I find the code from https://github.com/haosulab/ManiSkill2-Learn/blob/xmate-uncolored/submission_example/user_solution.py
