### ISSUE TITLE
There is a discrepancy of about 2 cm between the TCP pose planned by mplib and the final TCP pose read from the Franka robot

### ISSUE THREAD

**Issue by qiaojunyu** [haosulab/ManiSkill#472]
Great work and codebase, and I have developed something interesting using this simulator. When we use mplib to plan the trajectory of the Franka robot in the built-in environment, we input the target TCP pose, but find that the final TCP pose differs from the specified TCP pose by about 2 cm.

**Comment by StoneT2000** [comment]
Can you share an example? Is this a constant 2cm error or is it variable?

**Comment by TianxingChen** [comment]
I met the same error. It's variable. I don't know how to reduce this error, such as changing a specific threshold.

**Comment by StoneT2000** [comment]
It's hard to tell what the error is without it an example. If you are using the example motion planning code my guess is you might be tracking the wrong link. The panda arm has a invisible link called tcp or something which is a few centimeters below the end effector link

**Comment by StoneT2000** [comment]
Any update @qiaojunyu @TianxingChen for some example code to test to reproduce the problem?
