### ISSUE TITLE
Add `sapien.physx.PhysxMaterial` Parameter to Helper Functions to Build Primitive Shapes

### ISSUE THREAD

**Issue by hesic73** [haosulab/ManiSkill#474]
ManiSkill provides helper functions to build primitive shapes, such as `build_cube`:
https://github.com/haosulab/ManiSkill/blob/6b2cc48af337f0db61dc5eb1abae7ff49e530fe8/mani_skill/utils/building/actors/common.py#L26

Current implementation of `build_cube`:
```python
def build_cube(
    scene: ManiSkillScene,
    half_size: float,
    color,
    name: str,
    body_type: str = "dynamic",
    add_collision: bool = True,
):
    builder = scene.create_actor_builder()
    if add_collision:
        builder.add_box_collision(
            half_size=[half_size] * 3,
        )
    builder.add_box_visual(
        half_size=[half_size] * 3,
        material=sapien.render.RenderMaterial(
            base_color=color,
        ),
    )
    return _build_by_type(builder, name, body_type)

```

**Proposed change**:

Add a `physical_material: Optional[PhysxMaterial] = None` parameter to specify the physical properties of the actor:

```python
def build_cube(
    scene: ManiSkillScene,
    half_size: float,
    color,
    name: str,
    body_type: str = "dynamic",
    add_collision: bool = True,
    physical_material: Optional[PhysxMaterial] = None,
):
    builder = scene.create_actor_builder()
    if add_collision:
        builder.add_box_collision(
            half_size=[half_size] * 3,
            material=physical_material
        )
    builder.add_box_visual(
        half_size=[half_size] * 3,
        material=sapien.render.RenderMaterial(
            base_color=color,
        ),
    )
    return _build_by_type(builder, name, body_type)

```

**Reasons**:

- Users might want to specify `dynamic_friction`, `static_friction`, and `restitution` (or randomize these). It's a pity that the helper function doesn't support this.
- If users use the helper function to create a primitive shape **but don't know the physical parameters of the spawned actor**, they might get unwanted simulation results.

**Comment by StoneT2000** [comment]
Happy to merge this in! Feel free to make a PR

The helper functions are there mostly for convenience, usually for more advanced usage like setting physical parameters I recommend users to create the actor builders themselves and add collisions/visuals however they wish. But this is a welcome addition anyway.
