### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by RayYoh** [haosulab/ManiSkill#478]
Hi authors, I have followed the instructions for installing ManiSkill. My CUDA driver version is 535.183.01, and CUDA 11.7. I have also tried python3.9 and python3.10. When I try to test the environment, I get:
![image](https://github.com/user-attachments/assets/377e7649-e756-4895-98c0-60074392b927)

**Comment by RayYoh** [comment]
I updated torch, and it works.

**Comment by StoneT2000** [comment]
Didn't realize a older version of torch could cause a bug? Do you know what the previous version of torch was?

**Comment by RayYoh** [comment]
The previous version is 1.13.1+cu117
