### ISSUE TITLE
[BugFix] Add GPU IK solver fallback option

### ISSUE THREAD

**Issue by StoneT2000** [haosulab/ManiSkill#481]
Currently IK based controllers like pd_ee_delta_pos/pose on GPU sim might be bugged due to the fast kinematics package which i used to compute jacobians for fast end effector control. A fall back option is the slower (but more stable) pytorch kinematics which is python torch based. Would require forking that repo since https://github.com/UM-ARM-Lab/pytorch_kinematics/issues/35 is not resolved yet.

**Comment by davidemukpere** [comment]
hi, I've observed a hard to reproduce bug with GPU IK where sometimes the Jacobian returned contains zeros. is this similar to what you describe here and do you know what causes this?

**Comment by StoneT2000** [comment]
Yep it is one of them. I will probably add the fallback option / temporarily switch out fast kinematics this week. At the moment only the CPU IK solver works correctly.

**Comment by StoneT2000** [comment]
Feel free to try the latest commit now @siriusted @RomDeffayet, let me know if it is fixed

**Comment by RomDeffayet** [comment]
Thanks, unfortunately I get a device error in pytorch kinematics now during initialization: 

rot_h = torch.cat((rot, zeros), dim=-2).reshape(-1, 4, 3)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)

It seems to come from the fact that the device argument is set to 'cpu' by default and is not overwritten in pytorch_kinematics.urdf._convert_transform

It's on PK's side and only an issue when setting `torch.set_default_device` though

**Comment by StoneT2000** [comment]
Can you share a reproducible script?

**Comment by RomDeffayet** [comment]
```python
import torch
import mani_skill
import gymnasium

torch.set_default_device("cuda")
env = gymnasium.make("PushCube-v1", num_envs = 2, control_mode="pd_ee_delta_pose")
```


It is easily fixed by adding `device="cpu"` in pytorch_kinematics.urdf, line 17. I opened an issue on PK's repo for that.

**Comment by StoneT2000** [comment]
Oh i can fix it then. I currently have a fork of the pk library just for maniskill since they haven't yet fixed another issue where pk installs mujoco unnecessarily.

**Comment by StoneT2000** [comment]
I opened a PR to fix that (plus another small bug) on their repo. For the time being I updated my own fork of it on pypi so you can now do pip install pytorch_kinematics==0.7.3
