### ISSUE TITLE
Motionplanning GPU multi-env ? 

### ISSUE THREAD

**Issue by alexcbb** [haosulab/ManiSkill#494]
Hello, I was trying to use the motion planning examples in order to generate a dataset, but I didn't found a way yet to use it with multiple environment in parallel (with GPU parallelization). Is it something that is planned or already implemented ? It seems that it needs to be done in the `PandaArmMotionPlanningSolver` in [https://github.com/haosulab/ManiSkill/blob/main/mani_skill/examples/motionplanning/panda/motionplanner.py](url).

I don't know much about mplib but can it be used in a parallel fashion ? 

Thank you in advance !

**Comment by StoneT2000** [comment]
At the moment motion planning code is not GPU parallelized. You can try setting up cuRobo for that.

For motion planning if you want parallelization you will need to use multiprocessing
