### ISSUE TITLE
[Question]Motion Planning for Articulated Object link!

### ISSUE THREAD

**Issue by LongXinKou** [haosulab/ManiSkill#501]
Hello! I encountered an issue while using the **PandaArmMotionPlanningSolver** for path planning, specifically related to obtaining the bounding box of a link. When working with static objects(like mani_skill/examples/motionplanning/panda/solutions/pick_cube.py), I can obtain the **Actor's Bounding Box** using **get_actor_obb(env.obj)**. However, when trying to work with **articulated objects**, I can retrieve the Bounding Box of a link by **get_local_axis_aligned_bbox_for_link**, but it can not work for path planning like Actor.

Could you please guide me on how to properly handle articulated objects and effectively use the Bounding Box of a link? I would greatly appreciate your assistance.

Once again, thank you for your outstanding work and support!

**Comment by StoneT2000** [comment]
Can you share example code / bash script you ran and the error output?
