### ISSUE TITLE
Getting specific object pose in mobile manipulation scene

### ISSUE THREAD

**Issue by hq-sg** [haosulab/ManiSkill#510]
Thanks for the wonderful simulator. I am a little confused when I want to get the pose of a specific object in mobile manipulation scene. I understand that initial object pose can be extracted in scene builder, while I want to know when one of the object is manipulated by the Fetch robot, how to track the real-time pose of the object? Looking forward to your reply. Thanks again.

**Comment by StoneT2000** [comment]
check self.scene.actors which is a dict mapping actor name to actor objects. You can then fetch pose data from the actor objects

**Comment by hq-sg** [comment]
Great, thanks~
