### ISSUE TITLE
Rendering fails to due to segmentation on beta9

### ISSUE THREAD

**Issue by RomDeffayet** [haosulab/ManiSkill#530]
Hi, 
in this line:
https://github.com/haosulab/ManiSkill/blob/4fa913d2112d75952eea4ed525c6e1714b850ea3/mani_skill/sensors/camera.py#L282

torch.uint32 does not exist so rendering fails.

**Comment by StoneT2000** [comment]
What version of torch are you using?

**Comment by RomDeffayet** [comment]
I'm using 2.2.2, and it seems that uint32 has been introduced in 2.3

**Comment by StoneT2000** [comment]
Ah that would make sense. I would like to continue to support older torch versions so I'll try and make a patch for this later.
