### ISSUE TITLE
Missing demos/ Directory in ManiSkill2 v0.5.0

### ISSUE THREAD

**Issue by pumfish** [haosulab/ManiSkill#537]
I'm working on ManiSkill2 v0.5.0 and have found that my project is missing the ```demos/``` directory. I checked the **README** but did not find any information about this. Additionally, the links under **Demonstrations** are broken.

**Questions:**
- How can I obtain the ```demos/``` directory?
- Is there a step I might have missed, or is there an updated link or source for the demonstrations?
Thank you!

**Comment by StoneT2000** [comment]
See https://maniskill.readthedocs.io/en/v0.5.3-rtd/concepts/demonstrations.html, the docs link from before got moved

**Comment by pumfish** [comment]
> See https://maniskill.readthedocs.io/en/v0.5.3-rtd/concepts/demonstrations.html, the docs link from before got moved

Thank you very much for your reply. I’ll try it first to see if it works.
