### ISSUE TITLE
Extracting ee_delta_pose with motion planning

### ISSUE THREAD

**Issue by alexcbb** [haosulab/ManiSkill#542]
Hello,

For a specific use case, I'm searching to generate a dataset of trajectories containing end-effector delta poses as actions to achieve some tasks. For this, I want to collect data following the motion planning example that seems to use directly joint poses. It seems possible to get end-effector absolute positions (given the , but how can I possibly get the delta poses from step to step in order to extract the "ground truth actions" ? 

Thank you in advance !

**Comment by StoneT2000** [comment]
You can try using the replay trajectory tool: https://maniskill.readthedocs.io/en/latest/user_guide/datasets/replay.html

It is not guaranteed to get 100% conversion success rate from one action space (e.g. pd joint pos) to another (pd ee delta pose which is what you want). I might be able to improve the success rate of the tool down the line with some tricks but you it works well for easier tasks (like pick cube) but not highly precise tasks (e.g. plug charger).

**Comment by alexcbb** [comment]
Hello, unfortunately I tried this solution but for me the success rate is of 0% (even with a simple task that is a remix of pushcube). I tried  to understand why but didn't find a thing

**Comment by StoneT2000** [comment]
What command did you run? And how did you generate the demonstrations in the first place?

**Comment by alexcbb** [comment]
Here is the command that I launched : 
```
python -m mani_skill.trajectory.replay_trajectory \
  --traj-path path-tomy-traj/trajectory.h5 \
  --save-traj -c pd_ee_delta_pose \
 --vis \
  --obs-mode rgb
```
For generating the demonstrations I followed the example of [motion-planning](https://maniskill.readthedocs.io/en/latest/user_guide/data_collection/motionplanning.html) with panda robot here : https://github.com/haosulab/ManiSkill/tree/main/mani_skill/examples/motionplanning/panda 

I just have a model of Pushcube with additionnal distractor objects. I use the `PandaArmMotionPlanningSolver` to solve trajectories in order to push the cube to the target. Here is an example gif of the task solved (very similar to the push cube task): ![Screencastfrom02-09-2024101035-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/5a1c6bde-d780-4804-a1cc-666b33d5c982) My dataset is recorder with `pd_joint_pos` controller.

**Comment by StoneT2000** [comment]
This task should convert quite easily.

Can you try using the latest git commit of maniskill? This version looks a little out of date. I recently updated the replay trajectory tool to convert at a higher success rate for harder tasks.

Do you have a video of what the failed converged trajectory looks like?

**Comment by alexcbb** [comment]
Indeed but now it seems that one import is not updated : `from mani_skill.trajectory.utils.actions import conversion as action_conversion` is not present in the last commit of the main branch it seems.

**Comment by alexcbb** [comment]
I just updated to the last version and the problem still occurs. Here is an overview of a failed trajectory (the goal is to push the red cube to the target) : 
![Screencastfrom06-09-2024102152-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/a257f2e6-7215-41b1-874e-d437440854da)

**Comment by alexcbb** [comment]
I think I might get why the problem occurs. I believe this is due to the randomization process I apply at each episode reset. It's weird but even if with the provided seed, the scene seems to not replicate exactly as it was. I will investigate on my side, but it works better than before. Thank you again for your help !

**Comment by alexcbb** [comment]
Ok problem fixed, I just set the seed of numpy, torch and python to the right current seed and now everything works perfectly ! Thanks a lot for the help
