### ISSUE TITLE
[Question] Is there any method to get the "reward" information in Demonstration?

### ISSUE THREAD

**Issue by arainwong** [haosulab/ManiSkill#550]
Hi, 

In my experiment, I want to combine "behaviour cloning" and "Q learning" methods as the loss for an actor. 
Therefore, I need 'reward' information. I tried using the class ManiSkillDataset(Dataset) provided in bc.py, but the trajectory does not include rewards -> in detail: dict_keys(['obs', 'actions', 'terminated', 'truncated', 'success', 'env_states'])

However, based on the information revealed in https://maniskill.readthedocs.io/en/latest/user_guide/datasets/demos.html#loading-trajectory-datasets and the paper "ManiSkill2: A Unified Benchmark For Generalizable Manipulation Skills," it seems possible to generate trajectories that include 'reward' information. 

Therefore, I would like to ask how this can be implemented? 
Thank you very much!!

**Comment by StoneT2000** [comment]
Yeah it is possible. You can use the replay trajectory tool to replay a demo and record the rewards

e.g.

```bash
python -m mani_skill.trajectory.replay_trajectory \
  --traj-path path/to/demos/trajectory.h5 --use-env-states \
  --obs-mode state --num-procs 10 --record-rewards
```

I will also update the docs to reflect this use case: https://maniskill.readthedocs.io/en/latest/user_guide/datasets/replay.html
