### ISSUE TITLE
[Question] Accessing `Actor` or `Link` state in `_initialize_episode`

### ISSUE THREAD

**Issue by hesic73** [haosulab/ManiSkill#558]
In `_initialize_episode`, I'm able to access the state of an `Actor` or `Link` object. Previously, I set the robot's state and accessed the position of its link like this:
```python
self.agent.robot.set_state(agent_state, env_idx=env_idx)
palm_xyz = self.palm_link.pose.p
# use palm_xyz for other initialization
...
```

I incorrectly assumed the link's position is updated immediately after setting the state. Based on the implementation, it seems this assumption is wrong.
https://github.com/haosulab/ManiSkill/blob/532bb97357faef00a790b010b764f61f4f59333e/mani_skill/envs/sapien_env.py#L808

Is reading states in `_initialize_episode` generally undefined?
Or should I explicitly ensure the state updates by calling:
```python
if physx.is_gpu_enabled():
    # ensure all updates to object poses and configurations are applied on GPU after task initialization
    self.scene._gpu_apply_all()
    self.scene.px.gpu_update_articulation_kinematics()
    self.scene._gpu_fetch_all()
```

**Comment by StoneT2000** [comment]
Looks like our documentation could be updated on this topic. The state update code of apply all, update kinematics, then fetch all is required whenever you want to read up to date link poses.

In general, when setting object pose or velocity (which is what occurs when setting any kind of sim state, state only ever includes pose, velocities, qpos, qvels), this will live update that data on the python side so if you read actor poses, or articulation qpos values, they will be whatever you set them to. Link poses/velocities are the only thing that i am aware of that do not get live updated. Perfectly fine to read actor poses/velocities, just not links at the moment. This is done to ensure we call apply/fetch as little as possible for efficiency.

gpu_apply_all writes all of that data internally to GPU buffers that you can't read. gpu_update_articulation_kinematics will generate link pose/velocity data based articulation qpos values. gpu_fetch_all then reads those GPU buffers. If you want the live link pose info, just call apply all, update kinematics, and fetch all.
