### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by j-thapa** [haosulab/ManiSkill#566]
I am using windows and GPU, so it seems GPU simulation is not feasible; can we do multiple simulation on CPU? when i try to use sim_backend cpu for num_envs it shows error

**Comment by StoneT2000** [comment]
for CPU vectorization, the num_envs argument is not to be used as that is for GPU vectorization. Need to update the docs with CPU vectorization examples but there is example located here for RL setups: https://maniskill.readthedocs.io/en/latest/user_guide/reinforcement_learning/setup.html#evaluation

**Comment by j-thapa** [comment]
I forgot to mention, I am using Windows and I am trying to train using vector environments in the CPU; is it even feasible to do so. Cause while trying environment using above setup I got multiple errors.
