### ISSUE TITLE
[Bug] Slower CPU Simulation relative to ManiSkill2

### ISSUE THREAD

**Issue by StoneT2000** [haosulab/ManiSkill#590]
ManiSkill2 with 16 parallel envs can simulate somewhere in the 2-3k region FPS, but in ManiSkill3 with the CPU backend it drops down to around 1-2K FPS.

**Comment by uvenkatateja** [comment]
Hi @StoneT2000,

I would like to help fix this performance bug in the CPU simulation. Could you please assign this issue to me?

Thank you!

**Comment by StoneT2000** [comment]
Thanks for offering to help @uvenkatateja 

feel free to make a PR that fixes this
