### ISSUE TITLE
`parse_visual_obs_mode_to_struct` doesn't support obs_mode="sensor_data"

### ISSUE THREAD

**Issue by hesic73** [haosulab/ManiSkill#605]
https://github.com/haosulab/ManiSkill/blob/362d43d385da58e4bbeb06a6455e27c2006ecec9/mani_skill/envs/sapien_env.py#L114

https://github.com/haosulab/ManiSkill/blob/362d43d385da58e4bbeb06a6455e27c2006ecec9/mani_skill/envs/utils/observations/__init__.py#L14-L53

The [3D Diffusion Policy](https://github.com/YanjieZe/3D-Diffusion-Policy/) seems to require not only point cloud data and RGB images but also depth information, which `obs_mode="pointcloud"` doesn't support. Therefore, I expect the return value for `obs_mode="sensor_data"` should be:

```python
CameraObsTextures(
            rgb=True, depth=True, segmentation=True, position=True
        )
```

By the way, in the point cloud representation `xyzw`, what does the `w` stand for?

**Comment by StoneT2000** [comment]
w stand for infinite points, it's a mask. 0 is infinity points and shouldn't be used if it's a pointcloud / depth datapoint

Your fix is correct, feel free to make a PR to fix (currently away so can't get to it now)
