### ISSUE TITLE
Enhance Website Footer Design

### ISSUE THREAD

**Issue by Ananya54321** [haosulab/ManiSkill#609]
**Description**
The footer doesn't look very visually appealing. It occupies too much space but doesn't have a lot of helpful links/content in it.

**Screenshots**
<img width="1470" alt="Screenshot 2024-10-08 at 8 29 06 PM" src="https://github.com/user-attachments/assets/05a748e9-78e2-49ab-9493-88019d1fb041">

May I work on this issue?

**Comment by StoneT2000** [comment]
The website is not in this repo and the design is a decision between maintainers

**Comment by Ananya54321** [comment]
Ohh okay, my bad, thank you for letting me know!
