### ISSUE TITLE
Adjust Footer Height for Improved User Experience

### ISSUE THREAD

**Issue by Mefisto04** [haosulab/ManiSkill#624]
The current footer height is excessively tall, which negatively impacts the overall user experience. A footer that takes up too much vertical space can overwhelm users and detract from the main content of the page. 

**Proposed Changes:**

- Reduce the height of the footer to ensure it complements the main content without dominating the layout.
- Ensure that all essential information remains accessible and visually appealing within the adjusted footer space.

**Screenshot:**
![image](https://github.com/user-attachments/assets/e369ab98-9365-47fc-85ac-f541a9047a7f)

Please assign this issue to me so I can begin working on the necessary adjustments. Thank you!

**Comment by StoneT2000** [comment]
This is not necessary. Please check other issues first before posting. Request for changes to website have been addressed already.
