### ISSUE TITLE
No Robot Appears When Running python test.py -r uid

### ISSUE THREAD

**Issue by Luluoy** [haosulab/ManiSkill#644]
Hello,

In the tutorial found at (https://maniskill.readthedocs.io/en/latest/user_guide/tutorials/custom_robots.html#testing-the-loaded-urdf-mjcf，Testing The Loaded URDF/MJCF), I encountered an issue when running the command python test.py -r uid. The SAPIEN window does pop up during execution, but no robot appears in the simulation.

To verify that this issue is not related to my URDF file, I used the provided panda_v2.urdf file included in the project. However, the result is the same: the robot does not appear.

Could you please help me understand why this is happening? Thank you!

**Comment by Luluoy** [comment]
Solved, but keyframes must be set. However, this was not mentioned in the tutorials.

**Comment by StoneT2000** [comment]
Thanks for the bug spot, I have reopened it so that we can address this in the docs.
