### ISSUE TITLE
Pip install fails for python 3.13

### ISSUE THREAD

**Issue by BlGene** [haosulab/ManiSkill#646]
If you create a new conda env, you can get a python version of e.g. 3.13, for which there are no sapien versions, causing the installation of maniskill to fail, I got the error message below, as a solution downgrade to python 3.10.

Suggestion, specify the python version as 3.10 in the setup.py script.

```
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12
ERROR: Could not find a version that satisfies the requirement sapien==3.0.0.b1 (from mani-skill) (from versions: none)
ERROR: No matching distribution found for sapien==3.0.0.b1
```

**Comment by StoneT2000** [comment]
Python 3.9 to 3.11 should all work and are tested. I will ensure we do not permit 3.13

**Comment by StoneT2000** [comment]
Sorry I stand corrected

**Comment by StoneT2000** [comment]
Sorry actually we have a version of sapien that is built on 3.13, can you try installing this wheel instead?

https://github.com/haosulab/SAPIEN/releases/download/nightly/sapien-3.0.0.dev20241003+c877626f-cp313-cp313-manylinux2014_x86_64.whl

It is not on pypi yet.

**Comment by StoneT2000** [comment]
Hi @BlGene is this still an issue?

**Comment by BlGene** [comment]
Hi @StoneT2000 
thanks for checking in, no it's not. 

After downgradity to python 3.10 everything worked (w/ mani_skill 3.0.0b10 and  sapien 3.0.0b1), so I haven't changed my env. If you want me to double check, I can test a clean install (py 3.13 for you) tomorrow.
