### ISSUE TITLE
the discord link is expired

### ISSUE THREAD

**Issue by vncntt** [haosulab/ManiSkill#658]
^

**Comment by StoneT2000** [comment]
@vncntt which link? They seem to be working for me

**Comment by vncntt** [comment]
is the server public or are there permission settings? i was using the link in the readme

**Comment by StoneT2000** [comment]
https://discord.gg/x8yUZe5AdN this link? it is a public server

**Comment by vncntt** [comment]
hm the link worked from my phone but not my computer. probably a bug on my end. thanks
