### ISSUE TITLE
Ways to download datasets manually

### ISSUE THREAD

**Issue by SkyRainWind** [haosulab/ManiSkill#664]
Thanks for your brilliant works! When I use `download_and_replay_maniskill2.sh` to download datasets, however, the downloading process is way too slow (about 20kb/s), which muddles the usage.

The command needed is like `python -m mani_skill2.utils.download_demo -o ./demos/ all`, where we cannot watch sources clearly. Is it possible to give a explicit list for all used sources, so we can download manually?

**Comment by StoneT2000** [comment]
Are you using ManiSkill2 or ManiSkill3?

**Comment by SkyRainWind** [comment]
Yes I am using Maniskill2.

**Comment by StoneT2000** [comment]
https://huggingface.co/datasets/haosulab/ManiSkill2 has all the original maniskill2 demonstrations.
