### ISSUE TITLE
Lack of segmentation data in the "demo_vis_segmentation" example code

### ISSUE THREAD

**Issue by kevinqyh0827** [haosulab/ManiSkill#673]
Hi, when I tried the "demo_vis_segmentation" example code from tutorial. I got an error like this:
![image](https://github.com/user-attachments/assets/878686f9-eb6d-4678-b6de-5a70fa5e1b06)

It seems that the camera sensor data does not have the "segmentation" field. How could this to be fixed to access the segmentation data?

**Comment by StoneT2000** [comment]
thanks for the bug spot!
