### ISSUE TITLE
human rendering mode fails

### ISSUE THREAD

**Issue by noobiedoobiebopbop** [haosulab/ManiSkill#680]
following is the command I run. 

`python -m mani_skill.examples.demo_random_action -e "StackCube-v1" --render-mode "human"
`

And I get the following error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/me/.conda/envs/reset/lib/python3.12/site-packages/mani_skill/examples/demo_random_action.py", line 127, in <module>
    main(parsed_args)
  File "/home/me/.conda/envs/reset/lib/python3.12/site-packages/mani_skill/examples/demo_random_action.py", line 102, in main
    viewer = env.render()
             ^^^^^^^^^^^^
  File "/home/me/.conda/envs/reset/lib/python3.12/site-packages/gymnasium/core.py", line 471, in render
    return self.env.render()
           ^^^^^^^^^^^^^^^^^
  File "/home/me/.conda/envs/reset/lib/python3.12/site-packages/gymnasium/wrappers/order_enforcing.py", line 70, in render
    return self.env.render(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.conda/envs/reset/lib/python3.12/site-packages/mani_skill/envs/sapien_env.py", line 1285, in render
    return self.render_human()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/me/.conda/envs/reset/lib/python3.12/site-packages/mani_skill/envs/sapien_env.py", line 1220, in render_human
    self._viewer.render()
  File "/home/me/.conda/envs/reset/lib/python3.12/site-packages/sapien/utils/viewer/viewer.py", line 225, in render
    self.window.render(self.render_target, ui_windows)
RuntimeError: vk::Device::createSwapchainKHRUnique: ErrorOutOfDeviceMemory

The output of nvidia-smi

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:07:00.0 Off |                    0 |
| N/A   30C    P0             53W /  400W |     546MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     52721      G   /usr/libexec/Xorg                             108MiB |
|    0   N/A  N/A     52915      G   /usr/bin/gnome-shell                          136MiB |
|    0   N/A  N/A    809969    C+G   python                                        265MiB |
+-----------------------------------------------------------------------------------------+

Strangely, if I set render_mode as rgb_array, the rending runs without any problems. Any supervision would much be appreciated.

**Comment by StoneT2000** [comment]
human render mode requires a display. Other render modes return rgb images. Do you have a display attached to this machine?
