### ISSUE TITLE
Initialize the robot arm posture in a custom environment

### ISSUE THREAD

**Issue by CaiZedong** [haosulab/ManiSkill#694]
I followed the tutorial to load my custom robotic arm (panda's end effector was replaced with a dexterous hand) into the custom environment. The results I got by setting the keyframe 'rest' and running test.py were normal(picture below), but when I loaded the robotic arm into a custom environment, the initial position of the robotic arm was all joints = 0. How can I set the initial position of the robot arm in the custom environment to the keyframe position?
![1](https://github.com/user-attachments/assets/9878f189-ceb4-4912-9a13-f359659d6cdb)

**Comment by StoneT2000** [comment]
In your custom environment you should define a `def _initialize_episode` function which upon env.reset will initialize all objects accordingly including the robot. In this function you can do something like `self.agent.robot.set_qpos(self.agent.keyframes["rest"])`.

**Comment by CaiZedong** [comment]
Thank you very much, it's worked.
