### ISSUE TITLE
AttributeError: 'Viewer' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by fengjungui** [haosulab/ManiSkill#696]
When I use demo_manual_control.py,I meet this problem:
  **render_frame = env.render().cpu().numpy()[0]

  if after_reset:
      after_reset = False
      # Re-focus on opencv viewer
      if args.enable_sapien_viewer:
          renderer.close()
          renderer = visualization.ImageRenderer()
          pass
  # -------------------------------------------------------------------------- #
  # Interaction
  # -------------------------------------------------------------------------- #
  # Input
  renderer(render_frame)**

**Comment by StoneT2000** [comment]
What script did you run on the command line?

**Comment by fengjungui** [comment]
demo&nbsp;manual&nbsp;control


---Original---
From: &quot;Stone ***@***.***&gt;
Date: Fri, Nov 15, 2024 06:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [haosulab/ManiSkill] AttributeError: 'Viewer' object has noattribute 'cpu' (Issue #696)




 
What script did you run on the command line?
 
&mdash;

**Comment by StoneT2000** [comment]
I can't understand what you sent?
