### ISSUE TITLE
deno_manu_control TypeError: expected Tensor as element 1 in argument 0, but got int

### ISSUE THREAD

**Issue by fengjungui** [haosulab/ManiSkill#697]
def from_action_dict(self, action_dict: dict):
        """Convert a dict of actions to a flat action."""
        return torch.hstack([torch.tensor(action_dict[uid]) for uid in self.controllers])
        
        里面加一个[torch.tensor

**Comment by StoneT2000** [comment]
Can you share a full script?

**Comment by fengjungui** [comment]
I&nbsp;had.sovle&nbsp;this&nbsp;problem&nbsp;,because&nbsp;of&nbsp;the&nbsp;parameter&nbsp;of&nbsp;script.


---Original---
From: &quot;Stone ***@***.***&gt;
Date: Fri, Nov 15, 2024 06:41 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [haosulab/ManiSkill] deno_manu_control TypeError: expected Tensoras element 1 in argument 0, but got int (Issue #697)




 
Can you share a full script?
 
&mdash;

**Comment by StoneT2000** [comment]
I can't understand what you sent?
