### ISSUE TITLE
Model State Dimension Mismatch Between PushCube-v1 and PickCube-v1 Environments

### ISSUE THREAD

**Issue by songyuc** [haosulab/ManiSkill#710]
Hi,
When trying to evaluate a model trained on the `PushCube-v1` environment with the `PickCube-v1` environment, I encountered a state dimension mismatch error.

### Steps to Reproduce
1. First, trained the model using PushCube-v1:
```bash
python ppo_rgb.py --env_id="PushCube-v1" \
  --num_envs=256 --update_epochs=8 --num_minibatches=8 \
  --total_timesteps=1_000_000 --eval_freq=10 --num-steps=20
```

2. Then, tried to evaluate using PickCube-v1:
```bash
python ppo_rgb.py --env_id="PickCube-v1" \
  --evaluate --checkpoint=runs/PushCube-v1__ppo_rgb__1__1732109059/final_ckpt.pt \
  --num_eval_envs=1 --num-eval-steps=1000
```

### Error Message
```
RuntimeError: Error(s) in loading state_dict for Agent:
    size mismatch for feature_net.extractors.state.weight: copying a param with shape torch.Size([256, 25]) from checkpoint, the shape in current model is torch.Size([256, 29]).
```

### Environment
- OS: Ubuntu 22.04
- Python version: 3.11

### Questions
1. Is it expected that PushCube-v1 and PickCube-v1 have different state dimensions?
2. Is there a recommended way to handle model evaluation across different environments?
3. Should there be separate models for each environment type?

### Additional Information
The error suggests that PushCube-v1 has a state dimension of 25 while PickCube-v1 has 29. Is this by design?

**Comment by StoneT2000** [comment]
It is not expected that any two tasks will share the same state/observation dimensions. Action dimensions can be shared sometimes.

What is your use case? There are probably workarounds (for eg multi task learning).
