### ISSUE TITLE
Feature Request: Add environment mismatch warning in ppo_rgb.py

### ISSUE THREAD

**Issue by songyuc** [haosulab/ManiSkill#713]
Hi,
currently, when running `ppo_rgb.py`, if the environment used to train the model does not match the environment used for evaluation, it can lead to errors that are not immediately obvious to the user. This can cause confusion and waste time debugging.

I propose adding a warning message when `ppo_rgb.py` detects a mismatch between the environment used to train the model and the environment used for evaluation. This warning should include:

- The name of the environment used to train the model.
- The name of the environment used for evaluation.
- A message explaining that this mismatch may lead to inaccurate evaluation results.

It would also be helpful to check for mismatches in environment parameters such as observation and action space.

This feature will improve user experience and reduce the likelihood of errors caused by environment mismatches.

**Comment by StoneT2000** [comment]
a proper fix for this is to save some metadata in the model checkpoints / run folder like a json file describing the input arguments. This wasn't added since we stuck to trying to keep the code mostly a single file and simple
