### ISSUE TITLE
Query: Does ManiSkill support Python 3.12?

### ISSUE THREAD

**Issue by songyuc** [haosulab/ManiSkill#714]
Hi,
I am interested in using ManiSkill for a project that requires Python 3.12. However, the current installation instructions and dependencies do not explicitly mention support for this version.

### Questions
- Is Python 3.12 officially supported by ManiSkill?
- Are there any known issues or limitations with using Python 3.12?

### Additional Information
- Operating System: Ubuntu 20.04

**Comment by StoneT2000** [comment]
Python 3.11 is the recommended version that is most tested. You can try 3.12 though, and I'd be happy to help support it if needed
