### ISSUE TITLE
[Question] Headless HPC cluster, Multi-GPU and SLURM Compatibility

### ISSUE THREAD

**Issue by francescotaioli** [haosulab/ManiSkill#735]
Hi,
Thank you for your hard work on this project!

I have a question regarding the simulator's suitability for multi-GPU training (heavy models) on headless systems using SLURM. Specifically, I’m working on an HPC cluster that has the following restrictions:

- Docker is not allowed.

- Dependencies (e.g., vulkan) cannot be installed directly.
- Processes are launched exclusively via SLURM.

Could you provide guidance or point me to additional resources or code examples for this setup?

Thanks!

**Comment by StoneT2000** [comment]
Without docker or vulkan this is likely impossible to set up. Vulkan is required for any kind of rendering. And if you can't install vulkan as root docker is the next best option.
