### ISSUE TITLE
Documentation: Inconsistency in ppo.py torch_deterministic parameter comment

### ISSUE THREAD

**Issue by songyuc** [haosulab/ManiSkill#737]
Hi there,

I found a potential documentation issue in `examples/baselines/ppo/ppo.py`. There seems to be an inconsistency between the default value and the docstring for the `torch_deterministic` parameter:

```python
torch_deterministic: bool = True
"""if toggled, `torch.backends.cudnn.deterministic=False`"""
```

The default value is set to `True`, but the docstring suggests it would set `deterministic=False`, which appears contradictory.

Could you please verify if this is indeed a documentation error and update the comment to accurately reflect the parameter's behavior?

Thank you for maintaining this great project!

Best regards

**Comment by StoneT2000** [comment]
It should be left true. The speed gains with it false are very small and it's generally good to have reproducibility in RL. Happy to accept a PR to fix this
