### ISSUE TITLE
[Question] Can I get the contact point between an actor and a link?

### ISSUE THREAD

**Issue by hesic73** [haosulab/ManiSkill#738]
In ManiSkill, if there is a force between an actor and a link, can I obtain the point of application? Thanks!

**Comment by StoneT2000** [comment]
In GPU simulation this is not possible at the moment. In CPU it is but you might need to use the SAPIEN API for that. There's a get contacts function and each contacts object has details on the contact point exactly

**Comment by hesic73** [comment]
Thanks! I am working on some grasping tasks, and I am curious if I can give reward based on the contact point.
