### ISSUE TITLE
Unable to read VR Path Registry from C:\Users\26735\AppData\Local\openvr\openvrpaths.vrpath

### ISSUE THREAD

**Issue by xjtu19** [haosulab/ManiSkill#739]
When I run the command `pytest -vs` in the terminal, there is a notification (not an error):
`
tests/test_envs.py::test_all_envs[PickClutterYCB-v1] Unable to read VR Path Registry from C:\Users\26735\AppData\Local\openvr\openvrpaths.vrpath
PASSED
tests/test_envs.py::test_all_envs[PickCube-v1] Unable to read VR Path Registry from C:\Users\26735\AppData\Local\openvr\openvrpaths.vrpath
PASSED
tests/test_envs.py::test_all_envs[PickSingleYCB-v1] Unable to read VR Path Registry from C:\Users\26735\AppData\Local\openvr\openvrpaths.vrpath
PASSED
`
What dose it mean? And how to settle it?

**Comment by StoneT2000** [comment]
@fbxiang ?

**Comment by fbxiang** [comment]
It may have something to do with how openvr behaves on Windows (e.g. when Steam is installed, simply checking support for openvr may cause it to talk to Steam). I do not use Windows so I am not sure about the root cause. If it is just a harmless message, I would say just ignore it.
