### ISSUE TITLE
Request for Tutorial on Decomposing Non-Convex Objects into Convex Ones

### ISSUE THREAD

**Issue by ZZHLL** [haosulab/ManiSkill#748]
Hello,

I am currently working with dynamic non-convex objects in SAPIEN and encountered some issues with simulation performance.

When using the add_nonconvex_collision_from_file function to load dynamic non-convex objects, the simulation results are suboptimal. However, I observed that in the AssemblingKits-v1 environment, the add_multiple_collisions_from_file function achieves much better performance when loading dynamic non-convex objects. Could you provide guidance or a tutorial on how to decompose non-convex objects into convex components for better simulation results?

Additionally, I noticed that the developers mentioned in a discussion that convex decomposition functionality will be available in SAPIEN 3 ([Reference Link](https://github.com/haosulab/SAPIEN/discussions/127)). Could you share more details about this upcoming feature and its expected release timeline?

Any insights or resources would be greatly appreciated. Thank you!

**Comment by YZY14606** [comment]
Hello.  I also encountered the same problem. Can I ask how you solved it?
