### ISSUE TITLE
set_qpos doesn't work when running in GPU parallelization

### ISSUE THREAD

**Issue by TritiumR** [haosulab/ManiSkill#758]
Thanks for your amazing work and implementation for easy GPU parallelization.

I recently switched to GPU parallelization and encountered a bug that I can not reset the robots to original qpos by 
```
self.agent = self.env.unwrapped.agent
self.agent.robot.set_qpos(current_joint_angles)
```

It works well for the CPU simulation, as shown in the first video. But there is no reset behavior shown in the GPU simulation in the second video.

When I check the qpos by "self.agent.robot.get_qpos()" after setting it, the returned values also show that the robots **are not** reset to the same original qpos. 

Is there any bug with the set_qpos() in the GPU simulation. Are there any quick workaround that can help? (e.g., restore the whole environment to the previously saved one).

Thanks so much!

https://github.com/user-attachments/assets/de8f614b-0b74-41f8-acba-9229fe09e927

https://github.com/user-attachments/assets/118d7099-5798-4831-8bef-37775608e4d5

**Comment by StoneT2000** [comment]
where are you setting this value? With GPU simulation anything written outside of the initialize episode function to set gpu data should come with a gpu apply all call

**Comment by TritiumR** [comment]
I am setting outside of the initialize function, before env.step(action). Should I manually call the gpu apply all function or the set_qpos could handle it internally?

**Comment by TritiumR** [comment]
A quick question: should I just pass qpos with batch size one to the set_qpos() instead of repeat num_envs times in the first dimension?

**Comment by StoneT2000** [comment]
batch size 1 or repeated both should work, treat it like you are setting a batched torch tensor buffer representing the qpos

Try calling self.scene._gpu_apply_all() after setting qpos.

**Comment by TritiumR** [comment]
It didn't work

**Comment by StoneT2000** [comment]
Can run set qpos then apply all then run self.scene._gpu_fetch_all() then print the qpos? is it updated now?

**Comment by TritiumR** [comment]
Thanks so much! It kind of works, the qpos are updated and the poses look similar but the qpos is not exactly the values I set. Is that normal in GPU sim?

**Comment by TritiumR** [comment]
![Screenshot 2024-12-19 at 17 16 15](https://github.com/user-attachments/assets/2321de7a-bf7e-4ab2-918a-fb023028da5f)

**Comment by TritiumR** [comment]
There is still small deviation, is there any way to make the deviation smaller?

**Comment by StoneT2000** [comment]
Are you taking actions as well? And what controller are you using?

Or better can you share a code snippet of your environment loop?

**Comment by TritiumR** [comment]
Yes. I am using "pd_ee_delta_pose". I am trying to use CEM with GPU parallelization. Each time the actions are sampled from a distribution.

This is a pseudo code:
```
samples = np.random.multivariate_normal(means, covariance, size=args.num_sample_actions)
delta_scales = np.array([0.1, 0.1, 0.1, np.pi, np.pi, np.pi, 1])
sampled_delta_actions = samples * delta_scales

n = 30
for i in range(n)
        self.agent.robot.set_qpos(current_joint_angles) # (9,)
        self.env.scene._gpu_apply_all()
       
        obs, reward, terminated, truncated, info = self.env.step(actions) # (36, 7)

        current_joint_angles = self.agent.robot.get_qpos()[0]
```

Thank you so much

**Comment by StoneT2000** [comment]
Why does robot qpos need to be set? Is this because you are using CEM to explore action sequences then resetting back to a previous environment state to then take the best action?

**Comment by TritiumR** [comment]
Exactly

**Comment by StoneT2000** [comment]
Ok try using env.get_state_dict and env.set_state_dict (or get_state / set_state for flat tensors that you can batch and sample rows from)

You were only setting qpos doesn't cover joint velocity or object poses and velocities. This will really set the entire env state accordingly

**Comment by TritiumR** [comment]
Oh I see. It works perfectly right now. Thanks!
