### ISSUE TITLE
How to use pretrained policy weights for running inference on benchmarking script

### ISSUE THREAD

**Issue by rrzhang139** [haosulab/ManiSkill#764]
Hello, I'd like to visualize the PushCube-v1 task using the ppo pretrained weights downloaded from huggingface. Is there a simple script to run inference and output a video? I am using the `gpu_sim.py` benchmark script but I am not sure how to load the weights. Thank you!

**Comment by StoneT2000** [comment]
The examples/ppo/README.md describes how to run and evaluate a checkpoint generated by our PPO code and save videos
