### ISSUE TITLE
Adding new robots ?

### ISSUE THREAD

**Issue by jrabary** [haosulab/ManiSkill#80]
Hi, 
Thanks for making maniskill open. We are really interesting in using it to develop algorithms for robotic manipulation. But we'd like to deploy the policy on some low-cost robot like https://www.trossenrobotics.com/robotic-arms/ros-research-arms.aspx. Gazebo simulation exists for them. We are wondering how many effort will be needed to add them inside maniskill and if you can provide support for that.

**Comment by xuanlinli17** [comment]
Hi jrabary,

You can take a look at https://github.com/haosulab/ManiSkill2/blob/main/examples/tutorials/customize_environments.ipynb . There is a tutorial section for importing custom robots into maniskill2. Also see our implementation of Xmate3 as an example (`mani_skill2.agents.robots.xmate3`).

**Comment by StoneT2000** [comment]
https://github.com/haosulab/ManiSkill2/pull/175 will include a new, easier-to-read/easier-to-work-with robot API and some documentation around how robots are added. To be merged soon-ish
