### ISSUE TITLE
Installation fail: 

### ISSUE THREAD

**Issue by jiaming-ai** [haosulab/ManiSkill#89]
Hi,

I run the pip install command on a newly create conda env with python 3.9:

```
pip install mani-skill2
```

But it reports the following error:

========== normal part is ignored =======

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

===============================

It seems the required version of gym is not compatible with the new pip version.  I resolved this my removing the gym version specification in the requirement file and it seems successfully installed. Not sure if this is a solution for this.

**Comment by StoneT2000** [comment]
We will be fixing this officially in the v0.5.0 update with gymnasium but for you could you try 

pip install setuptools==65.5.0

**Comment by StoneT2000** [comment]
and then try install maniskill again

**Comment by jiaming-ai** [comment]
that solved the problem. thanks
