### ISSUE TITLE
Error from replaying trajectory of "PlugCharger-v0"

### ISSUE THREAD

**Issue by FredaZero** [haosulab/ManiSkill#95]
Hi,

I am training a model under "env=PlugCharger-v0", I wanted to convert the control mode from pd_joint_pos to pd_ee_delta_pos by running the replay_trajectory file, but it was unsuccessful, and it's the same story for replaying "PegInsertionSide-v0". Does it mean it's unchangeable? If I want to use end-effector control, do I have to manually compute the results from joint control data?

**Comment by xuanlinli17** [comment]
Could you post your script here?

**Comment by FredaZero** [comment]
> Could you post your script here? If you follow the scripts in ManiSkill2-Learn it shouldn't happen.

Thanks for replying.

I converted other task demonstrations to my desired control mode successfully with the following code:
`python -m mani_skill2.trajectory.replay_trajectory --traj-path ./demos/rigid_body/PegInsertionSide-v0/trajectory.h5 -o rgbd -c pd_ee_delta_pos --save-traj`

But when I am trying to convert PegInsertinSide-v0, it turns out:
![Screenshot from 2023-05-21 18-11-14](https://github.com/haosulab/ManiSkill2/assets/98103250/75dd2672-234e-4667-92e7-3d93deedd2e2)

**Comment by xuanlinli17** [comment]
Ok, I believe it's because you used `pd_ee_delta_pos` (3d ee xyz + 1d gripper), which can fail on some tasks where gripper rotation is required (e.g., PegInsertionSide, PlugCharger). However, if you use `pd_ee_delta_pose` (3d ee xyz + 3d ee rotation + 1d gripper), then it will be successful.

**Comment by FredaZero** [comment]
> Ok, I believe it's because you used `pd_ee_delta_pos` (3d ee xyz + 1d gripper), which can fail on some tasks where gripper rotation is required (e.g., PegInsertionSide, PlugCharger). However, if you use `pd_ee_delta_pose` (3d ee xyz + 3d ee rotation + 1d gripper), then it will be successful.

Thank you! It works now!
